# SALES TRACKER

### Import Libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
import warnings
warnings.filterwarnings('ignore')

# Import visualization libraries
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from scipy import stats

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.float_format', lambda x: f'{x:.2f}')

# Set plotting style
plt.style.use('seaborn-v0_8-darkgrid')
plt.rcParams['figure.figsize'] = (15, 10)
plt.rcParams['font.size'] = 10

print("✓ Libraries imported successfully")

✓ Libraries imported successfully

### Load Raw Data

In [2]:
# Load the raw sales tracker data
data_path = '../data/sales_tracker_inputs.csv'

# Check if file exists
if not os.path.exists(data_path):
    print(f"❌ Error: File not found at {data_path}")
    print("Please make sure the file exists in the data folder.")
else:
    # Read the CSV file
    df_raw = pd.read_csv(data_path)
    
    print("✓ Sales Tracker data loaded successfully")
    print(f"\nDataset shape: {df_raw.shape[0]} rows × {df_raw.shape[1]} columns")
    print(f"\nFirst few rows:")
    display(df_raw.head(5))

✓ Sales Tracker data loaded successfully

Dataset shape: 2020 rows × 26 columns

First few rows:

,2,Sale,Sale 2,Sale 3,Date,Sched. calls,Live calls,Offers,Deposit,Close 1,Close 2,Close 3,Month,Year,DoW #,DoW,Qtr,Show %,Offer %,Offer to Close %,Call to Close %,Rev. Gen.,Cash Collected,Week Key,Month Key,Notes
0,Derrick,NaN,NaN,NaN,5/1/24,5.00,5.00,5.00,0.00,0.00,0.00,0.00,5.00,2024.00,4.00,Wed,Q2,100.00%,100.00%,0.00%,0.00%,$ -,$ -,2024-W5,2024-05,NaN
1,Derrick,Orig. Deal,NaN,NaN,5/2/24,6.00,4.00,3.00,0.00,2.00,0.00,0.00,5.00,2024.00,5.00,Thu,Q2,66.67%,75.00%,66.67%,50.00%,$ -,$ -,2024-W5,2024-05,NaN
2,Derrick,Orig. Deal,NaN,NaN,5/3/24,5.00,5.00,4.00,0.00,1.00,0.00,0.00,5.00,2024.00,6.00,Fri,Q2,100.00%,80.00%,25.00%,20.00%,$ -,$ -,2024-W5,2024-05,NaN
3,Derrick,NaN,NaN,NaN,5/4/24,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.00,2024.00,7.00,Sat,Q2,0.00%,0.00%,0.00%,0.00%,$ -,$ -,2024-W5,2024-05,NaN
4,Derrick,NaN,NaN,NaN,5/5/24,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.00,2024.00,1.00,Sun,Q2,0.00%,0.00%,0.00%,0.00%,$ -,$ -,2024-W6,2024-05,NaN

### Inspect Data Structure

In [3]:
# Check if df_raw exists, if not, reload the data
try:
    df_raw.head()
except NameError:
    print("⚠️ df_raw not found. Loading data...")
    data_path = '../data/sales_tracker_inputs.csv'
    df_raw = pd.read_csv(data_path)
    print("✓ Data loaded successfully")

# Display data info
print("Sales Tracker Data Information:")
print("=" * 60)
df_raw.info()

print("\n" + "=" * 60)
print("Column Names:")
print("=" * 60)
for i, col in enumerate(df_raw.columns, 1):
    print(f"{i}. {col}")

print("\n" + "=" * 60)
print("Missing Values Check:")
print("=" * 60)
missing = df_raw.isnull().sum()
if missing.sum() == 0:
    print("✓ No missing values found")
else:
    print(missing[missing > 0])

print("\n" + "=" * 60)
print("Basic Statistics:")
print("=" * 60)
display(df_raw.describe())

Sales Tracker Data Information:
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   2                 2019 non-null   object
 1   Sale              757 non-null    object
 2   Sale 2            37 non-null     object
 3   Sale 3            1 non-null      object
 4   Date              2020 non-null   object
 5   Sched. calls      2019 non-null   float64
 6   Live calls        2018 non-null   float64
 7   Offers            2017 non-null   float64
 8   Deposit           526 non-null    float64
 9   Close 1           2018 non-null   float64
 10  Close 2           2012 non-null   float64
 11  Close 3           2010 non-null   float64
 12  Month             2016 non-null   float64
 13  Year              2016 non-null   float64
 14  DoW #             2016 non-null   float64
 15  DoW               2016 non-null   object
 16  Qtr               2016 non-null   object
 17  Show %            2016 non-null   object
 18  Offer %           2016 non-null   object
 19  Offer to Close %  2016 non-null   object
 20  Call to Close %   2016 non-null   object
 21  Rev. Gen.         2015 non-null   object
 22  Cash Collected    2007 non-null   object
 23  Week Key          2020 non-null   object
 24  Month Key         2020 non-null   object
 25  Notes             60 non-null     object
dtypes: float64(10), object(16)
memory usage: 410.4+ KB

============================================================
Column Names:
============================================================
1. 2
2. Sale
3. Sale 2
4. Sale 3
5. Date
6. Sched. calls
7. Live calls
8. Offers
9. Deposit
10. Close 1
11. Close 2
12. Close 3
13. Month
14. Year
15. DoW #
16. DoW
17. Qtr
18. Show %
19. Offer %
20. Offer to Close %
21. Call to Close %
22. Rev. Gen.
23. Cash Collected
24. Week Key
25. Month Key
26. Notes

============================================================
Missing Values Check:
============================================================
2                      1
Sale                1263
Sale 2              1983
Sale 3              2019
Sched. calls           1
Live calls             2
Offers                 3
Deposit             1494
Close 1                2
Close 2                8
Close 3               10
Month                  4
Year                   4
DoW #                  4
DoW                    4
Qtr                    4
Show %                 4
Offer %                4
Offer to Close %       4
Call to Close %        4
Rev. Gen.              5
Cash Collected        13
Notes               1960
dtype: int64

============================================================
Basic Statistics:
============================================================

,Sched. calls,Live calls,Offers,Deposit,Close 1,Close 2,Close 3,Month,Year,DoW #
count,2019.00,2018.00,2017.00,526.00,2018.00,2012.00,2010.00,2016.00,2016.00,2016.00
mean,3.34,2.50,1.80,0.05,0.44,0.02,0.00,7.28,2024.74,3.98
std,1.83,1.56,1.33,0.23,0.72,0.13,0.03,3.15,0.44,1.58
min,0.00,0.00,0.00,0.00,-1.00,0.00,0.00,1.00,2024.00,1.00
25%,2.00,1.00,1.00,0.00,0.00,0.00,0.00,5.00,2024.00,3.00
50%,3.00,2.00,2.00,0.00,0.00,0.00,0.00,8.00,2025.00,4.00
75%,5.00,4.00,3.00,0.00,1.00,0.00,0.00,10.00,2025.00,5.00
max,10.00,8.00,7.00,2.00,8.00,2.00,1.00,12.00,2025.00,7.00

### Process Raw Data - Clean and Prepare

In [4]:
# Create a working copy
df = df_raw.copy()

# Convert Date to datetime - handle different date formats
# Try to infer the format automatically
try:
    df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y')
except:
    try:
        df['Date'] = pd.to_datetime(df['Date'], format='mixed')
    except:
        # If both fail, try a more flexible approach
        df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# Check if any dates failed to parse
failed_dates = df['Date'].isna().sum()
if failed_dates > 0:
    print(f"⚠️ Warning: {failed_dates} dates could not be parsed and were set to NaT")
    print("Rows with invalid dates:")
    display(df[df['Date'].isna()])
    # Remove rows with invalid dates
    df = df.dropna(subset=['Date'])
    print(f"✓ Removed {failed_dates} rows with invalid dates")

# Extract just the date (remove any time component if present)
df['Date'] = df['Date'].dt.date

print("✓ Date processing complete")
print(f"\nDate range in dataset:")
print(f"  Earliest: {df['Date'].min()}")
print(f"  Latest: {df['Date'].max()}")
print(f"  Total days: {(df['Date'].max() - df['Date'].min()).days + 1} days")

print(f"\nUnique dates: {df['Date'].nunique()}")
print(f"Total rows: {len(df)}")
print(f"\nSample of processed data:")
display(df[['Date', 'Sched. calls', 'Live calls', 'Offers', 'Close 1', 'Show %', 'Offer %']].head(10))

✓ Date processing complete

Date range in dataset:
  Earliest: 2024-04-01
  Latest: 2025-12-13
  Total days: 622 days

Unique dates: 529
Total rows: 2020

Sample of processed data:

         Date  Sched. calls  Live calls  Offers  Close 1   Show %  Offer %
0  2024-05-01          5.00        5.00    5.00     0.00  100.00%  100.00%
1  2024-05-02          6.00        4.00    3.00     2.00   66.67%   75.00%
2  2024-05-03          5.00        5.00    4.00     1.00  100.00%   80.00%
3  2024-05-04          0.00        0.00    0.00     0.00    0.00%    0.00%
4  2024-05-05          0.00        0.00    0.00     0.00    0.00%    0.00%
5  2024-05-06          5.00        4.00    4.00     0.00   80.00%  100.00%
6  2024-05-07          5.00        3.00    3.00     0.00   60.00%  100.00%
7  2024-05-08          5.00        4.00    4.00     0.00   80.00%  100.00%
8  2024-05-09          4.00        3.00    2.00     1.00   75.00%   66.67%
9  2024-04-29          6.00        5.00    5.00     0.00   83.33%  100.00%

### Create Daily Aggregated Data

In [5]:
# Work with raw data
df_daily_prep = df_raw.copy()

# Extract just the date from Date
df_daily_prep['Date'] = pd.to_datetime(df_daily_prep['Date']).dt.date

# Convert percentage columns from string to float (remove % sign)
percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
for col in percentage_cols:
    if col in df_daily_prep.columns:
        df_daily_prep[col] = df_daily_prep[col].astype(str).str.replace('%', '').astype(float)

# Group by date and aggregate
df_daily = df_daily_prep.groupby('Date').agg({
    'Sched. calls': 'sum',
    'Live calls': 'sum',
    'Offers': 'sum',
    'Close 1': 'sum',
    'Show %': 'mean',  # Average the percentage from raw data
    'Offer %': 'mean',  # Average the percentage from raw data
    'Offer to Close %': 'mean',  # Average the percentage from raw data
    'Call to Close %': 'mean'  # Average the percentage from raw data
}).reset_index()

# Reorder columns (removed Live Call to Close %)
df_daily = df_daily[['Date', 'Sched. calls', 'Live calls', 'Offers', 'Close 1', 
                     'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']]

# Convert Date to datetime then format as MM/DD/YYYY
df_daily['Date'] = pd.to_datetime(df_daily['Date']).dt.strftime('%m/%d/%Y')

# Format percentages with % suffix
for col in percentage_cols:
    df_daily[col] = df_daily[col].round(2).astype(str) + '%'

print("✓ Daily data aggregated successfully")
print(f"\nDaily dataset shape: {df_daily.shape[0]} rows × {df_daily.shape[1]} columns")
print(f"\nFirst 5 days:")
display(df_daily.head(5))

print(f"\nLast 5 days:")
display(df_daily.tail(5))

✓ Daily data aggregated successfully

Daily dataset shape: 529 rows × 9 columns

First 5 days:

,Date,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,04/01/2024,6.00,5.00,3.00,0.00,83.33%,60.0%,0.0%,0.0%
1,04/02/2024,6.00,5.00,3.00,0.00,83.33%,60.0%,0.0%,0.0%
2,04/03/2024,4.00,3.00,1.00,0.00,75.0%,33.33%,0.0%,0.0%
3,04/04/2024,3.00,2.00,1.00,0.00,66.67%,50.0%,0.0%,0.0%
4,04/05/2024,2.00,2.00,1.00,0.00,100.0%,50.0%,0.0%,0.0%

Last 5 days:

,Date,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
524,12/09/2025,27.00,20.00,15.00,3.00,71.0%,67.5%,23.33%,23.33%
525,12/10/2025,43.00,33.00,21.00,3.00,78.06%,67.22%,25.0%,19.44%
526,12/11/2025,35.00,26.00,21.00,1.00,80.53%,72.78%,5.56%,5.56%
527,12/12/2025,21.00,16.00,12.00,2.00,65.0%,68.85%,25.0%,22.22%
528,12/13/2025,5.00,2.00,1.00,1.00,41.66%,50.0%,0.0%,50.0%

### Create Weekly Aggregated Data

In [6]:
# Work with raw data (not daily data)
df_weekly_prep = df_raw.copy()

# Convert Date to datetime
df_weekly_prep['Date'] = pd.to_datetime(df_weekly_prep['Date'])

# Convert percentage columns from string to float (remove % sign)
percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
for col in percentage_cols:
    if col in df_weekly_prep.columns:
        df_weekly_prep[col] = df_weekly_prep[col].astype(str).str.replace('%', '').astype(float)

# Create week identifier (week starting on Sunday)
df_weekly_prep['Week'] = df_weekly_prep['Date'] - pd.to_timedelta((df_weekly_prep['Date'].dt.dayofweek + 1) % 7, unit='D')

# Aggregate by week
df_weekly = df_weekly_prep.groupby('Week').agg({
    'Date': ['min', 'max'],
    'Sched. calls': 'sum',
    'Live calls': 'sum',
    'Offers': 'sum',
    'Close 1': 'sum',
    'Show %': 'mean',  # Average the percentage from raw data
    'Offer %': 'mean',  # Average the percentage from raw data
    'Offer to Close %': 'mean',  # Average the percentage from raw data
    'Call to Close %': 'mean'  # Average the percentage from raw data
}).reset_index()

# Flatten column names
df_weekly.columns = ['Week', 'Week_Start', 'Week_End', 'Sched. calls', 'Live calls', 
                     'Offers', 'Close 1', 'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']

# Create Week Number (sequential)
df_weekly['Week_Num'] = range(1, len(df_weekly) + 1)

# Format date range
df_weekly['Date Range'] = (df_weekly['Week_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                           df_weekly['Week_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns (removed Live Call to Close %)
df_weekly = df_weekly[['Week_Num', 'Date Range', 'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                       'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']]

# Rename Week_Num to Week
df_weekly.columns = ['Week', 'Date Range', 'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                     'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']

# Format percentages with % suffix
for col in percentage_cols:
    df_weekly[col] = df_weekly[col].round(2).astype(str) + '%'

print("✓ Weekly data aggregated successfully")
print(f"\nWeekly dataset shape: {df_weekly.shape[0]} rows × {df_weekly.shape[1]} columns")
print(f"\nFirst 5 weeks:")
display(df_weekly.head(5))

print(f"\nLast 5 weeks:")
display(df_weekly.tail(5))

✓ Weekly data aggregated successfully

Weekly dataset shape: 89 rows × 10 columns

First 5 weeks:

,Week,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,1,04/01/2024 - 04/05/2024,21.00,17.00,9.00,0.00,81.67%,50.67%,0.0%,0.0%
1,2,04/08/2024 - 04/12/2024,27.00,25.00,14.00,2.00,92.14%,56.67%,15.0%,6.67%
2,3,04/15/2024 - 04/19/2024,19.00,16.00,10.00,2.00,90.0%,67.0%,13.33%,9.0%
3,4,04/22/2024 - 04/27/2024,25.00,23.00,26.00,4.00,76.33%,92.5%,16.5%,20.0%
4,5,04/28/2024 - 05/04/2024,39.00,35.00,31.00,7.00,70.51%,68.97%,18.59%,14.36%

Last 5 weeks:

,Week,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
84,85,11/09/2025 - 11/15/2025,152.00,102.00,63.00,12.00,70.95%,58.92%,16.44%,11.49%
85,86,11/16/2025 - 11/22/2025,120.00,77.00,43.00,18.00,55.34%,43.64%,19.19%,12.73%
86,87,11/23/2025 - 11/29/2025,118.00,79.00,52.00,27.00,64.25%,58.65%,36.2%,35.52%
87,88,11/30/2025 - 12/06/2025,178.00,124.00,77.00,33.00,61.31%,56.27%,23.83%,20.4%
88,89,12/07/2025 - 12/13/2025,172.00,127.00,85.00,14.00,67.84%,61.38%,16.34%,15.36%

### Create Monthly Aggregated Data

In [7]:
# Work with raw data (not daily data)
df_monthly_prep = df_raw.copy()

# Convert Date to datetime
df_monthly_prep['Date'] = pd.to_datetime(df_monthly_prep['Date'])

# Convert percentage columns from string to float (remove % sign)
percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
for col in percentage_cols:
    if col in df_monthly_prep.columns:
        df_monthly_prep[col] = df_monthly_prep[col].astype(str).str.replace('%', '').astype(float)

# Extract year and month
df_monthly_prep['Year'] = df_monthly_prep['Date'].dt.year
df_monthly_prep['Month_Num'] = df_monthly_prep['Date'].dt.month
df_monthly_prep['Month_Name'] = df_monthly_prep['Date'].dt.strftime('%B')

# Create month identifier for grouping
df_monthly_prep['YearMonth'] = df_monthly_prep['Date'].dt.to_period('M')

# Aggregate by month
df_monthly = df_monthly_prep.groupby('YearMonth').agg({
    'Date': ['min', 'max'],
    'Month_Name': 'first',
    'Year': 'first',
    'Sched. calls': 'sum',
    'Live calls': 'sum',
    'Offers': 'sum',
    'Close 1': 'sum',
    'Show %': 'mean',  # Average the percentage from raw data
    'Offer %': 'mean',  # Average the percentage from raw data
    'Offer to Close %': 'mean',  # Average the percentage from raw data
    'Call to Close %': 'mean'  # Average the percentage from raw data
}).reset_index()

# Flatten column names
df_monthly.columns = ['YearMonth', 'Month_Start', 'Month_End', 'Month_Name', 'Year',
                      'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                      'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']

# Create Month label (e.g., "January 2025")
df_monthly['Month'] = df_monthly['Month_Name'] + ' ' + df_monthly['Year'].astype(str)

# Create Date Range
df_monthly['Date Range'] = (df_monthly['Month_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                            df_monthly['Month_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns (removed Live Call to Close %)
df_monthly = df_monthly[['Month', 'Date Range', 'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                         'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']]

# Format percentages with % suffix
for col in percentage_cols:
    df_monthly[col] = df_monthly[col].round(2).astype(str) + '%'

print("✓ Monthly data aggregated successfully")
print(f"\nMonthly dataset shape: {df_monthly.shape[0]} rows × {df_monthly.shape[1]} columns")
print(f"\nAll months:")
display(df_monthly.head(5))

✓ Monthly data aggregated successfully

Monthly dataset shape: 21 rows × 10 columns

All months:

,Month,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,April 2024,04/01/2024 - 04/30/2024,105.00,93.00,71.00,8.00,82.19%,73.22%,10.22%,9.28%
1,May 2024,05/01/2024 - 05/31/2024,165.00,138.00,120.00,26.00,79.87%,79.01%,24.26%,24.07%
2,June 2024,06/03/2024 - 06/28/2024,147.00,112.00,93.00,10.00,73.26%,74.11%,8.22%,6.74%
3,July 2024,07/01/2024 - 07/31/2024,179.00,157.00,135.00,25.00,85.86%,82.65%,15.33%,15.27%
4,August 2024,08/01/2024 - 08/30/2024,262.00,216.00,171.00,30.00,81.96%,74.71%,20.09%,16.74%

### Create Quarterly Aggregated Data

In [8]:
# Work with raw data (not daily data)
df_quarterly_prep = df_raw.copy()

# Convert Date to datetime
df_quarterly_prep['Date'] = pd.to_datetime(df_quarterly_prep['Date'])

# Convert percentage columns from string to float (remove % sign)
percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
for col in percentage_cols:
    if col in df_quarterly_prep.columns:
        df_quarterly_prep[col] = df_quarterly_prep[col].astype(str).str.replace('%', '').astype(float)

# Extract year and quarter
df_quarterly_prep['Year'] = df_quarterly_prep['Date'].dt.year
df_quarterly_prep['Quarter_Num'] = df_quarterly_prep['Date'].dt.quarter

# Create quarter identifier for grouping
df_quarterly_prep['YearQuarter'] = (df_quarterly_prep['Year'].astype(str) + 'Q' + 
                                    df_quarterly_prep['Quarter_Num'].astype(str))

# Aggregate by quarter
df_quarterly = df_quarterly_prep.groupby('YearQuarter').agg({
    'Date': ['min', 'max'],
    'Sched. calls': 'sum',
    'Live calls': 'sum',
    'Offers': 'sum',
    'Close 1': 'sum',
    'Show %': 'mean',  # Average the percentage from raw data
    'Offer %': 'mean',  # Average the percentage from raw data
    'Offer to Close %': 'mean',  # Average the percentage from raw data
    'Call to Close %': 'mean'  # Average the percentage from raw data
}).reset_index()

# Flatten column names
df_quarterly.columns = ['Quarter', 'Quarter_Start', 'Quarter_End',
                        'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                        'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']

# Create Date Range
df_quarterly['Date Range'] = (df_quarterly['Quarter_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                              df_quarterly['Quarter_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns (removed Live Call to Close %)
df_quarterly = df_quarterly[['Quarter', 'Date Range', 'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                             'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']]

# Format percentages with % suffix
for col in percentage_cols:
    df_quarterly[col] = df_quarterly[col].round(2).astype(str) + '%'

print("✓ Quarterly data aggregated successfully")
print(f"\nQuarterly dataset shape: {df_quarterly.shape[0]} rows × {df_quarterly.shape[1]} columns")
print(f"\nAll quarters:")
display(df_quarterly.head(5))

✓ Quarterly data aggregated successfully

Quarterly dataset shape: 7 rows × 10 columns

All quarters:

,Quarter,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,2024Q2,04/01/2024 - 06/28/2024,417.00,343.00,284.00,44.00,78.08%,75.91%,15.26%,14.44%
1,2024Q3,07/01/2024 - 09/30/2024,623.00,521.00,425.00,79.00,80.78%,75.96%,18.48%,17.2%
2,2024Q4,10/01/2024 - 12/31/2024,663.00,530.00,402.00,90.00,75.54%,70.51%,22.69%,18.51%
3,2025Q1,01/01/2025 - 03/31/2025,1196.00,851.00,629.00,103.00,66.26%,67.83%,16.02%,11.97%
4,2025Q2,04/01/2025 - 06/30/2025,1159.00,865.00,608.00,140.00,65.75%,61.05%,12.92%,11.44%

### Create Annual Aggregated Data

In [9]:
# Work with raw data (not daily data)
df_annual_prep = df_raw.copy()

# Convert Date to datetime
df_annual_prep['Date'] = pd.to_datetime(df_annual_prep['Date'])

# Convert percentage columns from string to float (remove % sign)
percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
for col in percentage_cols:
    if col in df_annual_prep.columns:
        df_annual_prep[col] = df_annual_prep[col].astype(str).str.replace('%', '').astype(float)

# Extract year
df_annual_prep['Year'] = df_annual_prep['Date'].dt.year

# Aggregate by year
df_annual = df_annual_prep.groupby('Year').agg({
    'Date': ['min', 'max'],
    'Sched. calls': 'sum',
    'Live calls': 'sum',
    'Offers': 'sum',
    'Close 1': 'sum',
    'Show %': 'mean',  # Average the percentage from raw data
    'Offer %': 'mean',  # Average the percentage from raw data
    'Offer to Close %': 'mean',  # Average the percentage from raw data
    'Call to Close %': 'mean'  # Average the percentage from raw data
}).reset_index()

# Flatten column names
df_annual.columns = ['Year', 'Year_Start', 'Year_End',
                     'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                     'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']

# Create Date Range
df_annual['Date Range'] = (df_annual['Year_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                           df_annual['Year_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns (removed Live Call to Close %)
df_annual = df_annual[['Year', 'Date Range', 'Sched. calls', 'Live calls', 'Offers', 'Close 1',
                       'Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']]

# Format percentages with % suffix
for col in percentage_cols:
    df_annual[col] = df_annual[col].round(2).astype(str) + '%'

print("✓ Annual data aggregated successfully")
print(f"\nAnnual dataset shape: {df_annual.shape[0]} rows × {df_annual.shape[1]} columns")
print(f"\nAll years:")
display(df_annual)

✓ Annual data aggregated successfully

Annual dataset shape: 2 rows × 10 columns

All years:

,Year,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,2024,04/01/2024 - 12/31/2024,1703.00,1394.00,1111.00,213.00,78.05%,73.78%,19.39%,17.06%
1,2025,01/01/2025 - 12/13/2025,5039.00,3646.00,2528.00,674.00,66.43%,61.13%,19.27%,16.25%

### Create Output Directory

In [10]:
# Define output directory path
output_dir = '../outputs/sales_tracker'

# Create the directory if it doesn't exist
os.makedirs(output_dir, exist_ok=True)

# Verify directory was created
if os.path.exists(output_dir):
    print(f"✓ Output directory created successfully: {output_dir}")
else:
    print(f"❌ Failed to create directory: {output_dir}")

✓ Output directory created successfully: ../outputs/sales_tracker

### Save All Datasets to CSV

In [11]:
# Save Daily data
daily_path = os.path.join(output_dir, 'daily_sales_tracker.csv')
df_daily.to_csv(daily_path, index=False)
print(f"✓ Saved: {daily_path}")
print(f"  Shape: {df_daily.shape[0]} rows × {df_daily.shape[1]} columns\n")

# Save Weekly data
weekly_path = os.path.join(output_dir, 'weekly_sales_tracker.csv')
df_weekly.to_csv(weekly_path, index=False)
print(f"✓ Saved: {weekly_path}")
print(f"  Shape: {df_weekly.shape[0]} rows × {df_weekly.shape[1]} columns\n")

# Save Monthly data
monthly_path = os.path.join(output_dir, 'monthly_sales_tracker.csv')
df_monthly.to_csv(monthly_path, index=False)
print(f"✓ Saved: {monthly_path}")
print(f"  Shape: {df_monthly.shape[0]} rows × {df_monthly.shape[1]} columns\n")

# Save Quarterly data
quarterly_path = os.path.join(output_dir, 'quarterly_sales_tracker.csv')
df_quarterly.to_csv(quarterly_path, index=False)
print(f"✓ Saved: {quarterly_path}")
print(f"  Shape: {df_quarterly.shape[0]} rows × {df_quarterly.shape[1]} columns\n")

# Save Annual data
annual_path = os.path.join(output_dir, 'annual_sales_tracker.csv')
df_annual.to_csv(annual_path, index=False)
print(f"✓ Saved: {annual_path}")
print(f"  Shape: {df_annual.shape[0]} rows × {df_annual.shape[1]} columns\n")

print("=" * 60)
print("✓ All datasets saved successfully!")
print("=" * 60)

✓ Saved: ../outputs/sales_tracker/daily_sales_tracker.csv
  Shape: 529 rows × 9 columns

✓ Saved: ../outputs/sales_tracker/weekly_sales_tracker.csv
  Shape: 89 rows × 10 columns

✓ Saved: ../outputs/sales_tracker/monthly_sales_tracker.csv
  Shape: 21 rows × 10 columns

✓ Saved: ../outputs/sales_tracker/quarterly_sales_tracker.csv
  Shape: 7 rows × 10 columns

✓ Saved: ../outputs/sales_tracker/annual_sales_tracker.csv
  Shape: 2 rows × 10 columns

============================================================
✓ All datasets saved successfully!
============================================================

### Verification - Preview Saved Files

In [12]:
# List all files in the output directory
print("Files in output directory:")
print("=" * 60)
for file in os.listdir(output_dir):
    file_path = os.path.join(output_dir, file)
    file_size = os.path.getsize(file_path) / 1024  # Size in KB
    print(f"  • {file:<35} ({file_size:.2f} KB)")

print("\n" + "=" * 60)
print("Preview of Daily Sales Tracker (first 10 rows):")
print("=" * 60)
df_verify_daily = pd.read_csv(daily_path)
display(df_verify_daily.head(3))

print("\n" + "=" * 60)
print("Preview of Daily Sales Tracker (last 10 rows):")
print("=" * 60)
display(df_verify_daily.tail(3))

print("\n" + "=" * 60)
print("Preview of Weekly Sales Tracker (first 10 rows):")
print("=" * 60)
df_verify_weekly = pd.read_csv(weekly_path)
display(df_verify_weekly.head(3))

print("\n" + "=" * 60)
print("Preview of Monthly Sales Tracker (all rows):")
print("=" * 60)
df_verify_monthly = pd.read_csv(monthly_path)
display(df_verify_monthly.head(3))

print("\n" + "=" * 60)
print("Preview of Quarterly Sales Tracker (all rows):")
print("=" * 60)
df_verify_quarterly = pd.read_csv(quarterly_path)
display(df_verify_quarterly.head(3))

print("\n" + "=" * 60)
print("Preview of Annual Sales Tracker (all rows):")
print("=" * 60)
df_verify_annual = pd.read_csv(annual_path)
display(df_verify_annual)

Files in output directory:
============================================================
  • weekly_sales_tracker.csv            (6.50 KB)
  • .DS_Store                           (6.00 KB)
  • custom_sales_tracker.csv            (0.24 KB)
  • quarterly_sales_tracker.csv         (0.67 KB)
  • monthly_sales_tracker.csv           (1.87 KB)
  • annual_sales_tracker.csv            (0.26 KB)
  • daily_sales_tracker.csv             (27.66 KB)

============================================================
Preview of Daily Sales Tracker (first 10 rows):
============================================================

,Date,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,04/01/2024,6.00,5.00,3.00,0.00,83.33%,60.0%,0.0%,0.0%
1,04/02/2024,6.00,5.00,3.00,0.00,83.33%,60.0%,0.0%,0.0%
2,04/03/2024,4.00,3.00,1.00,0.00,75.0%,33.33%,0.0%,0.0%

============================================================
Preview of Daily Sales Tracker (last 10 rows):
============================================================

,Date,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
526,12/11/2025,35.00,26.00,21.00,1.00,80.53%,72.78%,5.56%,5.56%
527,12/12/2025,21.00,16.00,12.00,2.00,65.0%,68.85%,25.0%,22.22%
528,12/13/2025,5.00,2.00,1.00,1.00,41.66%,50.0%,0.0%,50.0%

============================================================
Preview of Weekly Sales Tracker (first 10 rows):
============================================================

,Week,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,1,04/01/2024 - 04/05/2024,21.00,17.00,9.00,0.00,81.67%,50.67%,0.0%,0.0%
1,2,04/08/2024 - 04/12/2024,27.00,25.00,14.00,2.00,92.14%,56.67%,15.0%,6.67%
2,3,04/15/2024 - 04/19/2024,19.00,16.00,10.00,2.00,90.0%,67.0%,13.33%,9.0%

============================================================
Preview of Monthly Sales Tracker (all rows):
============================================================

,Month,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,April 2024,04/01/2024 - 04/30/2024,105.00,93.00,71.00,8.00,82.19%,73.22%,10.22%,9.28%
1,May 2024,05/01/2024 - 05/31/2024,165.00,138.00,120.00,26.00,79.87%,79.01%,24.26%,24.07%
2,June 2024,06/03/2024 - 06/28/2024,147.00,112.00,93.00,10.00,73.26%,74.11%,8.22%,6.74%

============================================================
Preview of Quarterly Sales Tracker (all rows):
============================================================

,Quarter,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,2024Q2,04/01/2024 - 06/28/2024,417.00,343.00,284.00,44.00,78.08%,75.91%,15.26%,14.44%
1,2024Q3,07/01/2024 - 09/30/2024,623.00,521.00,425.00,79.00,80.78%,75.96%,18.48%,17.2%
2,2024Q4,10/01/2024 - 12/31/2024,663.00,530.00,402.00,90.00,75.54%,70.51%,22.69%,18.51%

============================================================
Preview of Annual Sales Tracker (all rows):
============================================================

,Year,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,2024,04/01/2024 - 12/31/2024,1703.00,1394.00,1111.00,213.00,78.05%,73.78%,19.39%,17.06%
1,2025,01/01/2025 - 12/13/2025,5039.00,3646.00,2528.00,674.00,66.43%,61.13%,19.27%,16.25%

### Summary Statistics

In [13]:
print("\n" + "=" * 70)
print("SALES TRACKER DATA PROCESSING SUMMARY")
print("=" * 70)

print(f"\n📊 Data Processing Summary:")
print(f"  Total unique dates in raw data: {df_raw['Date'].nunique() if 'Date' in df_raw.columns else 'N/A'}")
print(f"  Total rows in raw data: {len(df_raw)}")
print(f"  Rows per day (average): {len(df_raw) / df_daily.shape[0]:.2f}")

print(f"\n📈 Aggregated Datasets Created:")
print(f"  Daily records: {df_daily.shape[0]}")
print(f"  Weekly records: {df_weekly.shape[0]}")
print(f"  Monthly records: {df_monthly.shape[0]}")
print(f"  Quarterly records: {df_quarterly.shape[0]}")
print(f"  Annual records: {df_annual.shape[0]}")

print(f"\n💾 Files Saved:")
print(f"  Location: {output_dir}")
print(f"  Total files: 5")

# Calculate total metrics from daily data (for verification)
df_daily_calc = df_daily.copy()
df_daily_calc['Show %'] = df_daily_calc['Show %'].str.rstrip('%').astype(float)
df_daily_calc['Offer %'] = df_daily_calc['Offer %'].str.rstrip('%').astype(float)
df_daily_calc['Offer to Close %'] = df_daily_calc['Offer to Close %'].str.rstrip('%').astype(float)
df_daily_calc['Call to Close %'] = df_daily_calc['Call to Close %'].str.rstrip('%').astype(float)
# REMOVED: df_daily_calc['Live Call to Close %'] line

print(f"\n📊 Overall Performance Metrics:")
print(f"  Total Scheduled Calls: {df_daily_calc['Sched. calls'].sum():,}")
print(f"  Total Live Calls: {df_daily_calc['Live calls'].sum():,}")
print(f"  Total Offers: {df_daily_calc['Offers'].sum():,}")
print(f"  Total Closes: {df_daily_calc['Close 1'].sum():,}")

print(f"\n📈 Overall Conversion Rates:")
print(f"  Average Show Rate: {df_daily_calc['Show %'].mean():.2f}%")
print(f"  Average Offer Rate: {df_daily_calc['Offer %'].mean():.2f}%")
print(f"  Average Offer to Close Rate: {df_daily_calc['Offer to Close %'].mean():.2f}%")
print(f"  Average Call to Close Rate: {df_daily_calc['Call to Close %'].mean():.2f}%")
# REMOVED: print Average Live Call to Close Rate line

print("\n" + "=" * 70)
print("✓ Sales Tracker data processing complete!")
print("=" * 70)

======================================================================
SALES TRACKER DATA PROCESSING SUMMARY
======================================================================

📊 Data Processing Summary:
  Total unique dates in raw data: 554
  Total rows in raw data: 2020
  Rows per day (average): 3.82

📈 Aggregated Datasets Created:
  Daily records: 529
  Weekly records: 89
  Monthly records: 21
  Quarterly records: 7
  Annual records: 2

💾 Files Saved:
  Location: ../outputs/sales_tracker
  Total files: 5

📊 Overall Performance Metrics:
  Total Scheduled Calls: 6,742.0
  Total Live Calls: 5,040.0
  Total Offers: 3,639.0
  Total Closes: 887.0

📈 Overall Conversion Rates:
  Average Show Rate: 68.80%
  Average Offer Rate: 65.06%
  Average Offer to Close Rate: 17.59%
  Average Call to Close Rate: 14.95%

======================================================================
✓ Sales Tracker data processing complete!
======================================================================

### Data Quality Check

In [14]:
print("\n" + "=" * 70)
print("DATA QUALITY VERIFICATION")
print("=" * 70)

# Check for any zero values in denominator columns
df_check = df_daily.copy()
df_check['Sched. calls'] = pd.to_numeric(df_check['Sched. calls'], errors='coerce')
df_check['Live calls'] = pd.to_numeric(df_check['Live calls'], errors='coerce')
df_check['Offers'] = pd.to_numeric(df_check['Offers'], errors='coerce')

print(f"\n🔍 Checking for potential data issues:")

# Days with zero scheduled calls
zero_sched = df_check[df_check['Sched. calls'] == 0]
if len(zero_sched) > 0:
    print(f"  ⚠️ Found {len(zero_sched)} days with 0 scheduled calls")
else:
    print(f"  ✓ No days with 0 scheduled calls")

# Days with zero live calls
zero_live = df_check[df_check['Live calls'] == 0]
if len(zero_live) > 0:
    print(f"  ⚠️ Found {len(zero_live)} days with 0 live calls")
else:
    print(f"  ✓ No days with 0 live calls")

# Days with zero offers
zero_offers = df_check[df_check['Offers'] == 0]
if len(zero_offers) > 0:
    print(f"  ⚠️ Found {len(zero_offers)} days with 0 offers")
else:
    print(f"  ✓ No days with 0 offers")

# Check for any inf or nan in percentage columns
print(f"\n🔍 Checking percentage calculations:")

for col in ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']:  # REMOVED 'Live Call to Close %'
    # Remove % sign and check
    values = df_daily[col].str.rstrip('%').astype(float)
    
    inf_count = np.isinf(values).sum()
    nan_count = values.isna().sum()
    
    if inf_count > 0 or nan_count > 0:
        print(f"  ⚠️ {col}: {inf_count} inf values, {nan_count} nan values")
    else:
        print(f"  ✓ {col}: All values valid")

print("\n" + "=" * 70)
print("✓ Data quality check complete!")
print("=" * 70)

======================================================================
DATA QUALITY VERIFICATION
======================================================================

🔍 Checking for potential data issues:
  ⚠️ Found 20 days with 0 scheduled calls
  ⚠️ Found 22 days with 0 live calls
  ⚠️ Found 28 days with 0 offers

🔍 Checking percentage calculations:
  ✓ Show %: All values valid
  ✓ Offer %: All values valid
  ✓ Offer to Close %: All values valid
  ✓ Call to Close %: All values valid

======================================================================
✓ Data quality check complete!
======================================================================

#

## Visualization

### Load Analysis Reference Dates

In [15]:
# Load analysis reference dates from CSV
analysis_ref = pd.read_csv('../analysis_ref_date.csv', header=None, names=['Reference', 'Value'])

# Extract dates
analysis_start = pd.to_datetime(analysis_ref[analysis_ref['Reference'] == 'Analysis Start Date']['Value'].values[0])
analysis_end = pd.to_datetime(analysis_ref[analysis_ref['Reference'] == 'Analysis End Date']['Value'].values[0])
quarter_start = pd.to_datetime(analysis_ref[analysis_ref['Reference'] == 'Quarter Start Date']['Value'].values[0])
quarter_end = pd.to_datetime(analysis_ref[analysis_ref['Reference'] == 'Quarter End Date']['Value'].values[0])

print("✓ Analysis dates loaded successfully")
print(f"\nDaily/Weekly/Monthly Analysis Period:")
print(f"  Start: {analysis_start.strftime('%m/%d/%Y')}")
print(f"  End: {analysis_end.strftime('%m/%d/%Y')}")
print(f"\nQuarterly/Annual Analysis Period:")
print(f"  Start: {quarter_start.strftime('%m/%d/%Y')}")
print(f"  End: {quarter_end.strftime('%m/%d/%Y')}")

✓ Analysis dates loaded successfully

Daily/Weekly/Monthly Analysis Period:
  Start: 01/01/2025
  End: 12/06/2025

Quarterly/Annual Analysis Period:
  Start: 01/01/2024
  End: 12/31/2025

### Load Target Reference Values

In [16]:
# Load target reference values
target_ref = pd.read_csv('../target_reference.csv')

# Create target dictionaries
monthly_targets = {}
quarterly_targets = {}
annual_targets = {}

# Extract targets
for _, row in target_ref.iterrows():
    metric = row['Metric']
    value = row['Target_Value']
    
    if 'Monthly' in metric:
        key = metric.replace('Monthly ', '')
        monthly_targets[key] = value
    elif 'Quarterly' in metric:
        key = metric.replace('Quarterly ', '')
        quarterly_targets[key] = value
    elif 'Annual' in metric:
        key = metric.replace('Annual ', '')
        annual_targets[key] = value

print("✓ Target values loaded successfully")

✓ Target values loaded successfully

### Create Visualization Directories

In [17]:
# Create output directories
viz_dirs = {
    'weekly': '../visualizations/sales_tracker_weekly',
    'monthly': '../visualizations/sales_tracker_monthly',
    'quarterly': '../visualizations/sales_tracker_quarterly',
    'annual': '../visualizations/sales_tracker_annual'
}

for name, path in viz_dirs.items():
    os.makedirs(path, exist_ok=True)
    print(f"✓ Created: {path}")

✓ Created: ../visualizations/sales_tracker_weekly
✓ Created: ../visualizations/sales_tracker_monthly
✓ Created: ../visualizations/sales_tracker_quarterly
✓ Created: ../visualizations/sales_tracker_annual

### Define XmR Chart Function (Weekly)

In [18]:
def plot_xmr_from_csv(
    csv_path,
    date_col,
    value_col,
    start_date=None,
    end_date=None,
    output_path=None,
    chart_title=None
):
    """
    Create XmR (Individuals and Moving Range) control charts with rule detection.
    Used for weekly analysis.
    """
    
    try:
        # Load data
        df = pd.read_csv(csv_path)
        print(f"✓ Loaded {len(df)} rows from {os.path.basename(csv_path)}")
        
        # Parse date column - handle both "Date" and "Date Range" formats
        if date_col == 'Date Range':
            # Extract start date from range (format: "MM/DD/YYYY - MM/DD/YYYY")
            df['Start_Date'] = df[date_col].str.split(' - ').str[0]
            df['Start_Date'] = pd.to_datetime(df['Start_Date'])
            df = df.sort_values('Start_Date').reset_index(drop=True)
            dates = df['Start_Date'].values
        else:
            df[date_col] = pd.to_datetime(df[date_col])
            df = df.sort_values(date_col).reset_index(drop=True)
            dates = df[date_col].values
        
        # Apply date range filter
        if start_date:
            start_dt = pd.to_datetime(start_date)
            if date_col == 'Date Range':
                df = df[df['Start_Date'] >= start_dt]
                dates = df['Start_Date'].values
            else:
                df = df[df[date_col] >= start_dt]
                dates = df[date_col].values
            print(f"✓ Filtered to dates >= {start_date}")
        
        if end_date:
            end_dt = pd.to_datetime(end_date)
            if date_col == 'Date Range':
                df = df[df['Start_Date'] <= end_dt]
                dates = df['Start_Date'].values
            else:
                df = df[df[date_col] <= end_dt]
                dates = df[date_col].values
            print(f"✓ Filtered to dates <= {end_date}")
        
        # Check if we have data
        if len(df) == 0:
            print(f"⚠️ No data available after filtering")
            return None
        
        # Extract X values (Individuals) - handle percentage strings
        if df[value_col].dtype == 'object' and '%' in str(df[value_col].iloc[0]):
            # Remove '%' and convert to float
            X = df[value_col].str.rstrip('%').astype(float).values
        else:
            X = df[value_col].values
        
        # Remove any NaN values
        valid_mask = ~np.isnan(X)
        X = X[valid_mask]
        dates = dates[valid_mask]
        
        if len(X) < 2:
            print(f"⚠️ Not enough data points ({len(X)}) to create XmR chart")
            return None
        
        print(f"✓ Analyzing {len(X)} data points")
        
        # Calculate Moving Range (mR)
        mR = np.abs(np.diff(X))
        
        # Calculate control limits
        X_mean = np.mean(X)
        mR_mean = np.mean(mR)
        
        # XmR constants (from Wheeler's formulas)
        UNPL = X_mean + 2.66 * mR_mean
        LNPL = X_mean - 2.66 * mR_mean
        
        # Calculate quartiles for Quartile Rule
        Q1 = X_mean - (0.6745 * 2.66 * mR_mean)
        Q3 = X_mean + (0.6745 * 2.66 * mR_mean)
        
        # Initialize color arrays
        colors = np.array(['black'] * len(X), dtype=object)
        point_sizes = np.array([40] * len(X))
        
        # RULE 1: Process Limit Rule
        process_limit_violations = []
        for i, val in enumerate(X):
            if val > UNPL or val < LNPL:
                colors[i] = 'red'
                point_sizes[i] = 100
                process_limit_violations.append(i)
        
        # RULE 2: Quartile Rule
        quartile_violations = []
        for i in range(len(X) - 3):
            upper_count = sum(1 for j in range(i, i+4) if X[j] > Q3)
            if upper_count >= 3:
                for j in range(i, i+4):
                    if colors[j] != 'red':
                        quartile_violations.append(j)
            
            lower_count = sum(1 for j in range(i, i+4) if X[j] < Q1)
            if lower_count >= 3:
                for j in range(i, i+4):
                    if colors[j] != 'red':
                        quartile_violations.append(j)
        
        for idx in set(quartile_violations):
            if colors[idx] != 'red':
                colors[idx] = 'orange'
                point_sizes[idx] = 80
        
        # RULE 3: Runs of 8 Rule
        runs_of_8_indices = []
        current_run_above = 0
        current_run_below = 0
        run_indices_above = []
        run_indices_below = []
        
        for i, val in enumerate(X):
            if val > X_mean:
                current_run_above += 1
                run_indices_above.append(i)
                current_run_below = 0
                run_indices_below = []
            elif val < X_mean:
                current_run_below += 1
                run_indices_below.append(i)
                current_run_above = 0
                run_indices_above = []
            else:
                current_run_above = 0
                current_run_below = 0
                run_indices_above = []
                run_indices_below = []
            
            if current_run_above >= 8:
                runs_of_8_indices.extend(run_indices_above[-8:])
            if current_run_below >= 8:
                runs_of_8_indices.extend(run_indices_below[-8:])
        
        for idx in set(runs_of_8_indices):
            if colors[idx] not in ['red', 'orange']:
                colors[idx] = 'blue'
                point_sizes[idx] = 70
        
        # Create visualization
        fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 10), 
                                       gridspec_kw={'height_ratios': [2.5, 1]})
        
        # X CHART (Individuals)
        ax1.plot(dates, X, '-', color='#333333', linewidth=1, zorder=1, alpha=0.6)
        
        for color in ['black', 'blue', 'orange', 'red']:
            mask = colors == color
            if np.any(mask):
                if color == 'red':
                    label = f'Process Limit Rule ({np.sum(mask)} points)'
                elif color == 'orange':
                    label = f'Quartile Rule ({np.sum(mask)} points)'
                elif color == 'blue':
                    label = f'Run of 8 Rule ({np.sum(mask)} points)'
                else:
                    label = f'Routine Variation ({np.sum(mask)} points)'
                
                ax1.scatter(dates[mask], X[mask], 
                           color=color, s=point_sizes[mask], 
                           zorder=3, label=label, 
                           edgecolors='white' if color != 'black' else 'none',
                           linewidths=1.5 if color != 'black' else 0)
        
        # Add value labels on points
        for i, (date, val) in enumerate(zip(dates, X)):
            ax1.text(date, val, f'{val:.1f}',
                    fontsize=7, ha='center', va='bottom',
                    color='#2C3E50', fontweight='bold')
        
        # Control limits
        ax1.axhline(X_mean, color='green', linestyle='-', linewidth=2, label=f'Mean: {X_mean:.2f}', zorder=2)
        ax1.axhline(UNPL, color='red', linestyle='--', linewidth=1.5, label=f'UNPL: {UNPL:.2f}', zorder=2)
        ax1.axhline(LNPL, color='red', linestyle='--', linewidth=1.5, label=f'LNPL: {LNPL:.2f}', zorder=2)
        ax1.axhline(Q1, color='orange', linestyle=':', linewidth=1, label=f'Q1: {Q1:.2f}', alpha=0.7, zorder=2)
        ax1.axhline(Q3, color='orange', linestyle=':', linewidth=1, label=f'Q3: {Q3:.2f}', alpha=0.7, zorder=2)
        
        # Formatting X chart
        ax1.set_ylabel('Value', fontsize=11, fontweight='bold')
        ax1.set_title(chart_title or 'XmR Control Chart', fontsize=13, fontweight='bold', pad=15)
        ax1.legend(loc='best', fontsize=8, ncol=2)
        ax1.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
        ax1.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
        plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45, ha='right')
        
        # mR CHART (Moving Range)
        mR_dates = dates[1:]  # mR has one less point
        URL_mR = mR_mean * 3.27
        
        ax2.plot(mR_dates, mR, '-o', color='#333333', linewidth=1, markersize=5, zorder=3)
        ax2.axhline(mR_mean, color='green', linestyle='-', linewidth=2, label=f'mR Mean: {mR_mean:.2f}', zorder=2)
        ax2.axhline(URL_mR, color='red', linestyle='--', linewidth=1.5, label=f'URL: {URL_mR:.2f}', zorder=2)
        
        # Formatting mR chart
        ax2.set_xlabel('Date', fontsize=11, fontweight='bold')
        ax2.set_ylabel('Moving Range', fontsize=11, fontweight='bold')
        ax2.legend(loc='best', fontsize=8)
        ax2.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
        ax2.xaxis.set_major_formatter(mdates.DateFormatter('%b %d'))
        plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45, ha='right')
        
        plt.tight_layout()
        
        # Save figure
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"✓ Chart saved to: {output_path}")
        
        plt.close(fig)
        
        # Print statistics
        print("\n" + "="*60)
        print(f"XmR CHART STATISTICS")
        print("="*60)
        print(f"Mean: {X_mean:.2f}")
        print(f"UNPL: {UNPL:.2f}")
        print(f"LNPL: {LNPL:.2f}")
        print(f"Q1: {Q1:.2f}, Q3: {Q3:.2f}")
        print(f"Moving Range Mean: {mR_mean:.2f}")
        print(f"URL (mR): {URL_mR:.2f}")
        print(f"\nRule Violations Detected:")
        print(f"  Rule 1 (Process Limit): {len(process_limit_violations)} points")
        print(f"  Rule 2 (Quartile): {len(set(quartile_violations))} points")
        print(f"  Rule 3 (Runs of 8): {len(set(runs_of_8_indices))} points")
        print(f"  Routine Variation: {np.sum(colors == 'black')} points")
        print("="*60 + "\n")
        
        return fig
        
    except Exception as e:
        print(f"❌ Error creating XmR chart: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

print("✓ XmR chart function defined")

✓ XmR chart function defined

### Define Monthly Chart Function

In [19]:
def create_monthly_chart(
    csv_path,
    date_col,
    metric_col,
    target_value,
    output_path,
    chart_title=None,
    metric_name=None,
    start_date=None,
    end_date=None
):
    """
    Create monthly chart with target line, prior-year average, and rolling 12-month trend.
    Shows MoM% changes.
    """
    
    try:
        # Load monthly data
        df = pd.read_csv(csv_path)
        print(f"✓ Loaded {len(df)} monthly records")
        
        # Extract month from the "Month" column (format: "January 2025")
        df['Month_Date'] = pd.to_datetime(df['Month'], format='%B %Y')
        df = df.sort_values('Month_Date').reset_index(drop=True)
        
        # Apply date range filter if specified
        if start_date:
            df = df[df['Month_Date'] >= start_date]
            print(f"✓ Filtered to dates >= {start_date.strftime('%Y-%m-%d')}")
        
        if end_date:
            df = df[df['Month_Date'] <= end_date]
            print(f"✓ Filtered to dates <= {end_date.strftime('%Y-%m-%d')}")
        
        # Exclude incomplete current month
        today = pd.Timestamp.now().normalize()
        current_month_start = pd.Timestamp(today.year, today.month, 1)
        df_complete = df[df['Month_Date'] < current_month_start].copy()
        
        excluded_count = len(df) - len(df_complete)
        if excluded_count > 0:
            print(f"⚠️ Excluded {excluded_count} records from incomplete current month ({today.strftime('%B %Y')})")
        
        df = df_complete
        
        if len(df) == 0:
            print("⚠️ No complete monthly data available")
            return None
        
        # Extract metric values - handle percentage strings
        if df[metric_col].dtype == 'object' and '%' in str(df[metric_col].iloc[0]):
            metric_values = df[metric_col].str.rstrip('%').astype(float).values
        else:
            metric_values = df[metric_col].values
        
        dates = df['Month_Date'].values
        
        print(f"✓ Visualizing {len(metric_values)} complete months")
        
        # Calculate Prior-Year Average
        if len(metric_values) >= 13:
            prior_year_avg = []
            for i in range(len(metric_values)):
                if i < 12:
                    prior_year_avg.append(np.nan)
                else:
                    avg = np.mean(metric_values[i-12:i])
                    prior_year_avg.append(avg)
            prior_year_avg = np.array(prior_year_avg)
        else:
            prior_year_avg = np.full(len(metric_values), np.nan)
        
        # Calculate Rolling 12-Month Average
        rolling_12m = []
        for i in range(len(metric_values)):
            if i < 11:
                rolling_12m.append(np.nan)
            else:
                avg = np.mean(metric_values[i-11:i+1])
                rolling_12m.append(avg)
        rolling_12m = np.array(rolling_12m)
        
        # Calculate MoM changes
        mom_changes = []
        for i in range(1, len(metric_values)):
            if metric_values[i-1] != 0:
                pct_change = ((metric_values[i] - metric_values[i-1]) / metric_values[i-1]) * 100
                mom_changes.append(pct_change)
        
        best_month_idx = np.argmax(metric_values)
        worst_month_idx = np.argmin(metric_values)
        
        # Create figure
        fig, ax = plt.subplots(figsize=(16, 8))
        
        # Plot monthly metric
        ax.plot(dates, metric_values, 
               color='black', linewidth=2.5, marker='o', markersize=8,
               label=f'Monthly {metric_name or metric_col}', zorder=4)
        
        # Plot target line if provided
        if target_value is not None:
            ax.axhline(target_value, color='red', linestyle='--', linewidth=2,
                      label=f'Target: {target_value:.2f}', zorder=2)
            print(f"✓ Target line added: {target_value:.2f}")
        
        # Plot prior-year average
        valid_prior_mask = ~np.isnan(prior_year_avg)
        if np.any(valid_prior_mask):
            ax.plot(dates[valid_prior_mask], prior_year_avg[valid_prior_mask],
                   color='#1f77b4', linestyle='--', linewidth=2,
                   label='Prior-Year Average', zorder=3)
        
        # Plot rolling 12-month trend
        valid_rolling_mask = ~np.isnan(rolling_12m)
        if np.any(valid_rolling_mask):
            ax.plot(dates[valid_rolling_mask], rolling_12m[valid_rolling_mask],
                   color='#7f7f7f', linestyle='-', linewidth=2, alpha=0.7,
                   label='Rolling 12-Month Trend', zorder=3)
        
        # Formatting
        ax.set_xlabel('Month', fontsize=12, fontweight='bold')
        ax.set_ylabel(metric_name or metric_col, fontsize=12, fontweight='bold')
        
        title = chart_title or f'Monthly {metric_name or metric_col} Performance'
        subtitle = 'Includes Target, Prior-Year Average, and Rolling 12-Month Trend'
        ax.set_title(f'{title}\n{subtitle}', fontsize=14, fontweight='bold', pad=20)
        
        ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
        ax.xaxis.set_major_locator(mdates.MonthLocator())
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha='right')
        
        ax.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
        ax.set_facecolor('white')
        fig.patch.set_facecolor('white')
        ax.legend(loc='best', fontsize=10, framealpha=0.95)
        
        plt.tight_layout()
        
        # Save figure
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"✓ Chart saved to: {output_path}")
        
        plt.close(fig)
        
        print("\n" + "="*60)
        print(f"MONTHLY SUMMARY: {metric_name or metric_col}")
        print("="*60)
        
        return fig
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

print("✓ Monthly chart function defined")

✓ Monthly chart function defined

### Define Quarterly Chart Function

In [20]:
def create_quarterly_chart(
    csv_path,
    metric_col,
    target_value,
    output_path,
    chart_title=None,
    metric_name=None
):
    """
    Create quarterly combo chart with bars, trend line, target, and prior-year average.
    Shows QoQ% changes.
    """
    
    try:
        # Load quarterly data
        df = pd.read_csv(csv_path)
        print(f"✓ Loaded {len(df)} quarterly records")
        
        # Sort by Quarter
        df = df.sort_values('Quarter').reset_index(drop=True)
        
        # Extract values
        quarters = df['Quarter'].values
        if df[metric_col].dtype == 'object' and '%' in str(df[metric_col].iloc[0]):
            metric_values = df[metric_col].str.rstrip('%').astype(float).values
        else:
            metric_values = df[metric_col].values
        date_ranges = df['Date Range'].values
        
        if len(metric_values) == 0:
            print("⚠️ No data to visualize")
            return None
        
        print(f"✓ Visualizing {len(metric_values)} quarters")
        
        # Calculate QoQ changes
        qoq_changes = []
        for i in range(1, len(metric_values)):
            if metric_values[i-1] != 0:
                pct_change = ((metric_values[i] - metric_values[i-1]) / metric_values[i-1]) * 100
                qoq_changes.append(pct_change)
            else:
                qoq_changes.append(np.nan)
        
        # Calculate Rolling 4-Quarter Average
        rolling_4q = []
        for i in range(len(metric_values)):
            if i < 3:
                rolling_4q.append(np.nan)
            else:
                avg = np.mean(metric_values[i-3:i+1])
                rolling_4q.append(avg)
        rolling_4q = np.array(rolling_4q)
        
        # Calculate Prior-Year Quarterly Average
        years = [int(q[:4]) for q in quarters]
        yearly_avg = {}
        for year in set(years):
            year_mask = [y == year for y in years]
            yearly_avg[year] = np.mean(metric_values[np.array(year_mask)])
        
        prior_year_avg = []
        for year in years:
            prior_year = year - 1
            if prior_year in yearly_avg:
                prior_year_avg.append(yearly_avg[prior_year])
            else:
                prior_year_avg.append(np.nan)
        prior_year_avg = np.array(prior_year_avg)
        
        # Create figure
        fig, ax = plt.subplots(figsize=(16, 9))
        
        # Create x positions for bars
        x_pos = np.arange(len(quarters))
        
        # Plot bars
        bars = ax.bar(x_pos, metric_values, 
                     color='#95A5A6', alpha=0.85, width=0.6,
                     edgecolor='#34495E', linewidth=2,
                     label=f'Quarterly {metric_name or metric_col}', zorder=2)
        
        # Add value labels on bars
        for i, (bar, value) in enumerate(zip(bars, metric_values)):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{value:.2f}',
                   ha='center', va='bottom', fontsize=11, fontweight='bold',
                   color='#2C3E50')
        
        # Plot rolling 4-quarter trend
        valid_rolling_mask = ~np.isnan(rolling_4q)
        if np.any(valid_rolling_mask):
            ax.plot(x_pos[valid_rolling_mask], rolling_4q[valid_rolling_mask],
                   color='#E67E22', linestyle='-', linewidth=3, marker='o', markersize=8,
                   label='Rolling 4-Quarter Trend', zorder=4)
        
        # Plot target line
        if target_value is not None:
            ax.axhline(target_value, color='red', linestyle='--', linewidth=2,
                      label=f'Target: {target_value:.2f}', zorder=3)
            print(f"✓ Target line added: {target_value:.2f}")
        
        # Plot prior-year average
        valid_prior_mask = ~np.isnan(prior_year_avg)
        if np.any(valid_prior_mask):
            prior_year_line = np.nanmean(prior_year_avg)
            ax.axhline(prior_year_line, color='#3498DB', linestyle='--', linewidth=2,
                      label=f'Prior-Year Average: {prior_year_line:.2f}', zorder=3)
        
        # Determine y-axis limits
        y_min = min(metric_values.min(), target_value if target_value else metric_values.min())
        y_max = max(metric_values.max(), target_value if target_value else metric_values.max())
        y_range = y_max - y_min
        
        has_qoq_labels = len(qoq_changes) > 0 and any(not np.isnan(qoq) for qoq in qoq_changes)
        bottom_padding = 0.18 if has_qoq_labels else 0.10
        ax.set_ylim(y_min - bottom_padding * y_range, y_max + 0.15 * y_range)
        
        # Add QoQ% labels
        if has_qoq_labels:
            for i, qoq in enumerate(qoq_changes):
                if not np.isnan(qoq):
                    color = '#27AE60' if qoq >= 0 else '#E74C3C'
                    y_position = y_min - 0.06 * y_range
                    ax.text(x_pos[i+1], y_position,
                           f'QoQ: {qoq:+.1f}%',
                           ha='center', va='top', fontsize=9, 
                           color=color, fontweight='bold')
        
        # Add date range labels
        for i, (pos, date_range) in enumerate(zip(x_pos, date_ranges)):
            y_position = y_min - 0.12 * y_range if has_qoq_labels else y_min - 0.05 * y_range
            ax.text(pos, y_position,
                   date_range,
                   ha='center', va='top', fontsize=9,
                   style='italic', color='#2C3E50',
                   fontweight='bold')
        
        # Formatting
        ax.set_xlabel('Quarter', fontsize=12, fontweight='bold')
        ax.set_ylabel(metric_name or metric_col, fontsize=12, fontweight='bold')
        
        title = chart_title or f'Quarterly {metric_name or metric_col} Performance'
        subtitle = 'Bars: Quarterly Values | Orange Line: Rolling 4-Quarter Trend | QoQ: Quarter-over-Quarter Change'
        ax.set_title(f'{title}\n{subtitle}', fontsize=14, fontweight='bold', pad=20)
        
        ax.set_xticks(x_pos)
        ax.set_xticklabels(quarters, rotation=45, ha='right', fontsize=10)
        
        ax.grid(True, alpha=0.3, linestyle='-', linewidth=0.5, axis='y')
        ax.set_facecolor('white')
        fig.patch.set_facecolor('white')
        ax.legend(loc='best', fontsize=10, framealpha=0.95)
        
        plt.tight_layout()
        
        # Save figure
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"✓ Chart saved to: {output_path}")
        
        plt.close(fig)
        
        return fig
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

print("✓ Quarterly chart function defined")

✓ Quarterly chart function defined

### Define Annual Chart Function

In [21]:
def create_annual_chart(
    csv_path,
    metric_col,
    target_value,
    output_path,
    chart_title=None,
    metric_name=None
):
    """
    Create annual bar chart with target line, trend line, and YoY% changes.
    Handles incomplete current year.
    """
    
    try:
        # Load annual data
        df = pd.read_csv(csv_path)
        print(f"✓ Loaded {len(df)} annual records")
        
        # Sort by year
        df = df.sort_values('Year').reset_index(drop=True)
        
        # Extract values
        years = df['Year'].values
        if df[metric_col].dtype == 'object' and '%' in str(df[metric_col].iloc[0]):
            metric_values = df[metric_col].str.rstrip('%').astype(float).values
        else:
            metric_values = df[metric_col].values
        date_ranges = df['Date Range'].values
        
        # Determine which years are complete
        today = pd.Timestamp.now()
        current_year = today.year
        year_complete = ['Yes' if year < current_year else 'No' for year in years]
        
        if len(metric_values) == 0:
            print("⚠️ No data to visualize")
            return None
        
        print(f"✓ Visualizing {len(metric_values)} years")
        
        # Calculate YoY changes
        yoy_changes = []
        for i in range(1, len(metric_values)):
            if metric_values[i-1] != 0:
                pct_change = ((metric_values[i] - metric_values[i-1]) / metric_values[i-1]) * 100
                yoy_changes.append(pct_change)
            else:
                yoy_changes.append(np.nan)
        
        # Calculate linear regression trend line
        trend_values = None
        if len(years) >= 2:
            slope, intercept, r_value, p_value, std_err = stats.linregress(years, metric_values)
            trend_values = slope * years + intercept
            print(f"✓ Trend line: slope={slope:.4f}, R²={r_value**2:.4f}")
        
        # Create figure
        fig, ax = plt.subplots(figsize=(16, 9))
        
        # Create x positions for bars
        x_pos = np.arange(len(years))
        
        # Color bars differently for complete vs incomplete years
        bar_colors = ['#34495E' if complete == 'Yes' else '#95A5A6' for complete in year_complete]
        
        # Plot bars
        bars = ax.bar(x_pos, metric_values, 
                     color=bar_colors, alpha=0.8, width=0.6,
                     edgecolor='white', linewidth=1.5, zorder=2)
        
        # Add value labels on bars
        for i, (bar, value, complete) in enumerate(zip(bars, metric_values, year_complete)):
            height = bar.get_height()
            label_text = f'{value:.2f}'
            if complete == 'No':
                label_text += '*'  # Add asterisk for incomplete years
            
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   label_text,
                   ha='center', va='bottom', fontsize=11, fontweight='bold')
        
        # Plot target line
        if target_value is not None:
            ax.axhline(target_value, color='red', linestyle='--', linewidth=2.5,
                      label=f'Target: {target_value:.2f}', zorder=3)
            print(f"✓ Target line added: {target_value:.2f}")
        
        # Plot trend line
        if trend_values is not None:
            ax.plot(x_pos, trend_values,
                   color='#E74C3C', linestyle='-', linewidth=2.5,
                   label='Trend Line (Linear)', zorder=4)
        
        # Determine y-axis limits
        y_min = min(metric_values.min(), target_value if target_value else metric_values.min())
        y_max = max(metric_values.max(), target_value if target_value else metric_values.max())
        y_range = y_max - y_min
        
        has_yoy_labels = len(yoy_changes) > 0 and any(not np.isnan(yoy) for yoy in yoy_changes)
        bottom_padding = 0.18 if has_yoy_labels else 0.10
        ax.set_ylim(y_min - bottom_padding * y_range, y_max + 0.15 * y_range)
        
        # Add YoY% labels
        if has_yoy_labels:
            for i, yoy in enumerate(yoy_changes):
                if not np.isnan(yoy):
                    color = '#27AE60' if yoy >= 0 else '#E74C3C'
                    y_position = y_min - 0.06 * y_range
                    ax.text(x_pos[i+1], y_position,
                           f'YoY: {yoy:+.1f}%',
                           ha='center', va='top', fontsize=9, 
                           color=color, fontweight='bold')
        
        # Add date range labels
        for i, (pos, date_range) in enumerate(zip(x_pos, date_ranges)):
            y_position = y_min - 0.12 * y_range if has_yoy_labels else y_min - 0.05 * y_range
            ax.text(pos, y_position,
                   date_range,
                   ha='center', va='top', fontsize=8,
                   style='italic', color='#555555')
        
        # Create custom legend
        from matplotlib.patches import Patch
        from matplotlib.lines import Line2D
        legend_elements = []
        
        legend_elements.append(Patch(facecolor='#34495E', label='Complete Year'))
        legend_elements.append(Patch(facecolor='#95A5A6', label='Incomplete Year (YTD)*'))
        
        if target_value is not None:
            legend_elements.append(Line2D([0], [0], color='red', linestyle='--', 
                                         linewidth=2.5, label=f'Target: {target_value:.2f}'))
        
        if trend_values is not None:
            legend_elements.append(Line2D([0], [0], color='#E74C3C', linestyle='-', 
                                         linewidth=2.5, label='Trend Line'))
        
        # Formatting
        ax.set_xlabel('Year', fontsize=13, fontweight='bold')
        ax.set_ylabel(metric_name or metric_col, fontsize=13, fontweight='bold')
        
        title = chart_title or f'Annual {metric_name or metric_col} Performance'
        subtitle = 'Bars: Annual Values | YoY: Year-over-Year Change | *Incomplete Year (YTD)'
        ax.set_title(f'{title}\n{subtitle}', fontsize=15, fontweight='bold', pad=20)
        
        ax.set_xticks(x_pos)
        ax.set_xticklabels(years.astype(int), fontsize=12, fontweight='bold')
        
        ax.grid(True, alpha=0.2, linestyle='-', linewidth=0.5, axis='y')
        ax.set_facecolor('white')
        fig.patch.set_facecolor('white')
        ax.legend(handles=legend_elements, loc='best', fontsize=11, framealpha=0.95)
        
        plt.tight_layout()
        
        # Save figure
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            plt.savefig(output_path, dpi=300, bbox_inches='tight', facecolor='white')
            print(f"✓ Chart saved to: {output_path}")
        
        plt.close(fig)
        
        return fig
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return None

print("✓ Annual chart function defined")

✓ Annual chart function defined

### Generate ALL Charts

In [22]:
print("\n" + "=" * 70)
print("GENERATING ALL SALES TRACKER CHARTS")
print("=" * 70)

# Define metrics
metrics = [
    ('Sched. calls', 'Scheduled Calls'),
    ('Live calls', 'Live Calls'),
    ('Show %', 'Show %'),
    ('Close 1', 'Closes'),
    ('Offers', 'Offers'),
    ('Offer %', 'Offer %'),
    ('Offer to Close %', 'Offer to Close %'),
    ('Call to Close %', 'Call to Close %')
]

# WEEKLY CHARTS
print("\n📊 Generating Weekly Charts...")
for metric_col, metric_name in metrics:
    plot_xmr_from_csv(
        csv_path='../outputs/sales_tracker/weekly_sales_tracker.csv',
        date_col='Date Range',
        value_col=metric_col,
        start_date=analysis_start,
        end_date=analysis_end,
        output_path=f"{viz_dirs['weekly']}/weekly_{metric_col.lower().replace(' ', '_').replace('.', '').replace('%', 'pct')}.png",
        chart_title=f'Sales Tracker - {metric_name} (Weekly XmR Chart)'
    )

# MONTHLY CHARTS
print("\n📊 Generating Monthly Charts...")
for metric_col, metric_name in metrics:
    target = monthly_targets.get(metric_col)
    create_monthly_chart(
        csv_path='../outputs/sales_tracker/monthly_sales_tracker.csv',
        date_col='Month',
        metric_col=metric_col,
        target_value=target,
        output_path=f"{viz_dirs['monthly']}/monthly_{metric_col.lower().replace(' ', '_').replace('.', '').replace('%', 'pct')}.png",
        chart_title=f'Sales Tracker - {metric_name} (Monthly Trend)',
        metric_name=metric_name,
        start_date=analysis_start,
        end_date=analysis_end
    )

# QUARTERLY CHARTS
print("\n📊 Generating Quarterly Charts...")
for metric_col, metric_name in metrics:
    target = quarterly_targets.get(metric_col)
    create_quarterly_chart(
        csv_path='../outputs/sales_tracker/quarterly_sales_tracker.csv',
        metric_col=metric_col,
        target_value=target,
        output_path=f"{viz_dirs['quarterly']}/quarterly_{metric_col.lower().replace(' ', '_').replace('.', '').replace('%', 'pct')}.png",
        chart_title=f'Sales Tracker - {metric_name} (Quarterly)',
        metric_name=metric_name
    )

# ANNUAL CHARTS
print("\n📊 Generating Annual Charts...")
for metric_col, metric_name in metrics:
    target = annual_targets.get(metric_col)
    create_annual_chart(
        csv_path='../outputs/sales_tracker/annual_sales_tracker.csv',
        metric_col=metric_col,
        target_value=target,
        output_path=f"{viz_dirs['annual']}/annual_{metric_col.lower().replace(' ', '_').replace('.', '').replace('%', 'pct')}.png",
        chart_title=f'Sales Tracker - {metric_name} (Annual)',
        metric_name=metric_name
    )

print("\n" + "=" * 70)
print("✓ ALL CHARTS GENERATED SUCCESSFULLY!")
print("=" * 70)

======================================================================
GENERATING ALL SALES TRACKER CHARTS
======================================================================

📊 Generating Weekly Charts...
✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_sched_calls.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 100.60
UNPL: 145.26
LNPL: 55.95
Q1: 70.49, Q3: 130.72
Moving Range Mean: 16.79
URL (mR): 54.89

Rule Violations Detected:
  Rule 1 (Process Limit): 3 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 10 points
  Routine Variation: 35 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_live_calls.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 72.71
UNPL: 105.31
LNPL: 40.11
Q1: 50.72, Q3: 94.70
Moving Range Mean: 12.26
URL (mR): 40.07

Rule Violations Detected:
  Rule 1 (Process Limit): 1 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 9 points
  Routine Variation: 38 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_show_pct.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 66.19
UNPL: 88.92
LNPL: 43.45
Q1: 50.85, Q3: 81.52
Moving Range Mean: 8.55
URL (mR): 27.95

Rule Violations Detected:
  Rule 1 (Process Limit): 0 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 0 points
  Routine Variation: 48 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_close_1.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 13.65
UNPL: 29.27
LNPL: -1.97
Q1: 3.11, Q3: 24.18
Moving Range Mean: 5.87
URL (mR): 19.20

Rule Violations Detected:
  Rule 1 (Process Limit): 2 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 20 points
  Routine Variation: 26 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_offers.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 50.52
UNPL: 77.01
LNPL: 24.03
Q1: 32.66, Q3: 68.39
Moving Range Mean: 9.96
URL (mR): 32.56

Rule Violations Detected:
  Rule 1 (Process Limit): 0 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 0 points
  Routine Variation: 48 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_offer_pct.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 61.59
UNPL: 88.03
LNPL: 35.14
Q1: 43.75, Q3: 79.42
Moving Range Mean: 9.94
URL (mR): 32.51

Rule Violations Detected:
  Rule 1 (Process Limit): 0 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 21 points
  Routine Variation: 27 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_offer_to_close_pct.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 18.79
UNPL: 44.51
LNPL: -6.93
Q1: 1.45, Q3: 36.14
Moving Range Mean: 9.67
URL (mR): 31.62

Rule Violations Detected:
  Rule 1 (Process Limit): 0 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 8 points
  Routine Variation: 40 points
============================================================

✓ Loaded 89 rows from weekly_sales_tracker.csv
✓ Filtered to dates >= 2025-01-01 00:00:00
✓ Filtered to dates <= 2025-12-06 00:00:00
✓ Analyzing 48 data points
✓ Chart saved to: ../visualizations/sales_tracker_weekly/weekly_call_to_close_pct.png

============================================================
XmR CHART STATISTICS
============================================================
Mean: 15.82
UNPL: 37.36
LNPL: -5.71
Q1: 1.30, Q3: 30.35
Moving Range Mean: 8.10
URL (mR): 26.47

Rule Violations Detected:
  Rule 1 (Process Limit): 0 points
  Rule 2 (Quartile): 0 points
  Rule 3 (Runs of 8): 0 points
  Routine Variation: 48 points
============================================================


📊 Generating Monthly Charts...
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_sched_calls.png

============================================================
MONTHLY SUMMARY: Scheduled Calls
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_live_calls.png

============================================================
MONTHLY SUMMARY: Live Calls
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Target line added: 68.00
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_show_pct.png

============================================================
MONTHLY SUMMARY: Show %
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_close_1.png

============================================================
MONTHLY SUMMARY: Closes
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Target line added: nan
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_offers.png

============================================================
MONTHLY SUMMARY: Offers
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Target line added: 65.00
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_offer_pct.png

============================================================
MONTHLY SUMMARY: Offer %
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Target line added: 20.00
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_offer_to_close_pct.png

============================================================
MONTHLY SUMMARY: Offer to Close %
============================================================
✓ Loaded 21 monthly records
✓ Filtered to dates >= 2025-01-01
✓ Filtered to dates <= 2025-12-06
⚠️ Excluded 1 records from incomplete current month (December 2025)
✓ Visualizing 11 complete months
✓ Target line added: 50.00
✓ Chart saved to: ../visualizations/sales_tracker_monthly/monthly_call_to_close_pct.png

============================================================
MONTHLY SUMMARY: Call to Close %
============================================================

📊 Generating Quarterly Charts...
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_sched_calls.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_live_calls.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Target line added: 72.00
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_show_pct.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_close_1.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Target line added: nan
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_offers.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Target line added: 65.00
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_offer_pct.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Target line added: 20.00
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_offer_to_close_pct.png
✓ Loaded 7 quarterly records
✓ Visualizing 7 quarters
✓ Target line added: 75.00
✓ Chart saved to: ../visualizations/sales_tracker_quarterly/quarterly_call_to_close_pct.png

📊 Generating Annual Charts...
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=3336.0000, R²=1.0000
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_sched_calls.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=2252.0000, R²=1.0000
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_live_calls.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=-11.6200, R²=1.0000
✓ Target line added: 75.00
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_show_pct.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=461.0000, R²=1.0000
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_close_1.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=1417.0000, R²=1.0000
✓ Target line added: nan
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_offers.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=-12.6500, R²=1.0000
✓ Target line added: 75.00
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_offer_pct.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=-0.1200, R²=1.0000
✓ Target line added: 25.00
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_offer_to_close_pct.png
✓ Loaded 2 annual records
✓ Visualizing 2 years
✓ Trend line: slope=-0.8100, R²=1.0000
✓ Target line added: 100.00
✓ Chart saved to: ../visualizations/sales_tracker_annual/annual_call_to_close_pct.png

======================================================================
✓ ALL CHARTS GENERATED SUCCESSFULLY!
======================================================================

#

## CUSTOM DATE RANGE ANALYSIS

### Load Custom Date Range Parameters

In [23]:
# Load analysis reference dates from CSV
ref_dates_path = '../analysis_ref_date.csv'

# Check if file exists
if not os.path.exists(ref_dates_path):
    print(f"❌ Error: File not found at {ref_dates_path}")
    custom_start = None
    custom_end = None
else:
    # Load reference dates
    ref_dates = pd.read_csv(ref_dates_path, header=None)
    
    # Parse custom date range
    custom_start = None
    custom_end = None
    
    for idx, row in ref_dates.iterrows():
        if row[0] == 'Custom Start Date':
            try:
                custom_start = pd.to_datetime(row[1])
            except:
                custom_start = None
        elif row[0] == 'Custom End Date':
            try:
                custom_end = pd.to_datetime(row[1])
            except:
                custom_end = None
    
    print(f"Custom Date Range:")
    print(f"  Start: {custom_start if custom_start else 'Not specified'}")
    print(f"  End: {custom_end if custom_end else 'Not specified'}")
    
    if custom_start and custom_end:
        date_range_days = (custom_end - custom_start).days + 1
        print(f"  Duration: {date_range_days} days")
    else:
        print("\n⚠️ Custom date range not properly specified in analysis_ref_date.csv")

Custom Date Range:
  Start: 2025-11-01 00:00:00
  End: 2025-11-28 00:00:00
  Duration: 28 days

### Generate Custom Date Range Sales Data

In [24]:
print("\n" + "="*70)
print("CUSTOM DATE RANGE SALES TRACKER AGGREGATION (WITH PREVIOUS PERIOD)")
print("="*70 + "\n")

if custom_start and custom_end:
    # Calculate previous period dates - shift back by ONE MONTH, keeping same day-of-month
    from dateutil.relativedelta import relativedelta
    
    prev_start = custom_start - relativedelta(months=1)
    prev_end = custom_end - relativedelta(months=1)
    
    # Calculate duration for display
    date_range_duration = (custom_end - custom_start).days + 1
    
    print(f"Current Period: {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')} ({date_range_duration} days)")
    print(f"Previous Period: {prev_start.strftime('%m/%d/%Y')} - {prev_end.strftime('%m/%d/%Y')} ({date_range_duration} days)\n")
    
    # Work with DAILY aggregated data for filtering
    df_custom_prep = df_daily.copy()
    
    # Remove % sign from percentage columns for calculation
    percentage_cols = ['Show %', 'Offer %', 'Offer to Close %', 'Call to Close %']
    for col in percentage_cols:
        if col in df_custom_prep.columns:
            df_custom_prep[col] = df_custom_prep[col].str.rstrip('%').astype(float)
    
    # Convert Date to datetime
    df_custom_prep['Date'] = pd.to_datetime(df_custom_prep['Date'])
    
    # Filter data for CURRENT custom date range
    df_custom_filtered = df_custom_prep[
        (df_custom_prep['Date'] >= custom_start) & 
        (df_custom_prep['Date'] <= custom_end)
    ].copy()
    
    # Filter data for PREVIOUS custom date range
    df_prev_filtered = df_custom_prep[
        (df_custom_prep['Date'] >= prev_start) & 
        (df_custom_prep['Date'] <= prev_end)
    ].copy()
    
    # Create empty list to store rows
    custom_rows = []
    
    # Process CURRENT period
    if len(df_custom_filtered) > 0:
        # Calculate the actual start and end dates from filtered data
        actual_start = df_custom_filtered['Date'].min()
        actual_end = df_custom_filtered['Date'].max()
        
        # Aggregate the filtered data
        total_sched_calls = df_custom_filtered['Sched. calls'].sum()
        total_live_calls = df_custom_filtered['Live calls'].sum()
        total_offers = df_custom_filtered['Offers'].sum()
        total_close1 = df_custom_filtered['Close 1'].sum()
        
        # Calculate AVERAGE percentages from DAILY data (NOT from raw data)
        avg_show_pct = df_custom_filtered['Show %'].mean()
        avg_offer_pct = df_custom_filtered['Offer %'].mean()
        avg_offer_to_close_pct = df_custom_filtered['Offer to Close %'].mean()
        avg_call_to_close_pct = df_custom_filtered['Call to Close %'].mean()
        
        current_row = {
            'Date Range': f"{actual_start.strftime('%m/%d/%Y')} - {actual_end.strftime('%m/%d/%Y')}",
            'Sched. calls': total_sched_calls,
            'Live calls': total_live_calls,
            'Offers': total_offers,
            'Close 1': total_close1,
            'Show %': f"{round(avg_show_pct, 2)}%",
            'Offer %': f"{round(avg_offer_pct, 2)}%",
            'Offer to Close %': f"{round(avg_offer_to_close_pct, 2)}%",
            'Call to Close %': f"{round(avg_call_to_close_pct, 2)}%"
        }
        custom_rows.append(current_row)
        
        print(f"✅ Current period data found: {len(df_custom_filtered)} days")
        print(f"   Total Scheduled Calls: {total_sched_calls:,.0f}")
        print(f"   Total Live Calls: {total_live_calls:,.0f}")
        print(f"   Total Offers: {total_offers:,.0f}")
        print(f"   Total Close 1: {total_close1:,.0f}")
        
    else:
        print(f"⚠️ No data for current period: {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')}")
    
    # Process PREVIOUS period
    if len(df_prev_filtered) > 0:
        # Calculate the actual start and end dates from filtered data
        actual_start = df_prev_filtered['Date'].min()
        actual_end = df_prev_filtered['Date'].max()
        
        # Aggregate the filtered data
        total_sched_calls = df_prev_filtered['Sched. calls'].sum()
        total_live_calls = df_prev_filtered['Live calls'].sum()
        total_offers = df_prev_filtered['Offers'].sum()
        total_close1 = df_prev_filtered['Close 1'].sum()
        
        # Calculate AVERAGE percentages from DAILY data (NOT from raw data)
        avg_show_pct = df_prev_filtered['Show %'].mean()
        avg_offer_pct = df_prev_filtered['Offer %'].mean()
        avg_offer_to_close_pct = df_prev_filtered['Offer to Close %'].mean()
        avg_call_to_close_pct = df_prev_filtered['Call to Close %'].mean()
        
        prev_row = {
            'Date Range': f"{actual_start.strftime('%m/%d/%Y')} - {actual_end.strftime('%m/%d/%Y')}",
            'Sched. calls': total_sched_calls,
            'Live calls': total_live_calls,
            'Offers': total_offers,
            'Close 1': total_close1,
            'Show %': f"{round(avg_show_pct, 2)}%",
            'Offer %': f"{round(avg_offer_pct, 2)}%",
            'Offer to Close %': f"{round(avg_offer_to_close_pct, 2)}%",
            'Call to Close %': f"{round(avg_call_to_close_pct, 2)}%"
        }
        custom_rows.append(prev_row)
        
        print(f"✅ Previous period data found: {len(df_prev_filtered)} days")
        print(f"   Total Scheduled Calls: {total_sched_calls:,.0f}")
        print(f"   Total Live Calls: {total_live_calls:,.0f}")
        print(f"   Total Offers: {total_offers:,.0f}")
        print(f"   Total Close 1: {total_close1:,.0f}")
        
    else:
        print(f"⚠️ No data for previous period: {prev_start.strftime('%m/%d/%Y')} - {prev_end.strftime('%m/%d/%Y')}")
    
    # Create final dataframe
    if len(custom_rows) > 0:
        df_custom = pd.DataFrame(custom_rows)
        
        # Display the results
        print("\n" + "="*70)
        print("Custom Date Range Sales Tracker Data (with Previous Period):")
        print("="*70)
        display(df_custom)
        
    else:
        print("\n⚠️ No data available for either current or previous period")
        df_custom = None
        
else:
    print("❌ Cannot generate custom analysis - dates not properly specified")
    print("   Please check Custom Start Date and Custom End Date in analysis_ref_date.csv")
    df_custom = None

print("\n" + "="*70)

======================================================================
CUSTOM DATE RANGE SALES TRACKER AGGREGATION (WITH PREVIOUS PERIOD)
======================================================================

Current Period: 11/01/2025 - 11/28/2025 (28 days)
Previous Period: 10/01/2025 - 10/28/2025 (28 days)

✅ Current period data found: 28 days
   Total Scheduled Calls: 493
   Total Live Calls: 338
   Total Offers: 207
   Total Close 1: 67
✅ Previous period data found: 25 days
   Total Scheduled Calls: 408
   Total Live Calls: 306
   Total Offers: 200
   Total Close 1: 65

======================================================================
Custom Date Range Sales Tracker Data (with Previous Period):
======================================================================

,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,11/01/2025 - 11/28/2025,493.00,338.00,207.00,67.00,56.09%,47.43%,23.5%,17.13%
1,10/01/2025 - 10/28/2025,408.00,306.00,200.00,65.00,70.65%,59.53%,19.97%,17.48%

======================================================================

### Save Custom Date Range Data

In [25]:
if df_custom is not None and len(df_custom) > 0:
    # Save to CSV
    custom_path = os.path.join(output_dir, 'custom_sales_tracker.csv')
    df_custom.to_csv(custom_path, index=False)
    
    print("\n" + "="*70)
    print("CUSTOM DATE RANGE ANALYSIS - COMPLETE")
    print("="*70)
    
    print(f"\n✅ OUTPUT CREATED:")
    print(f"  - custom_sales_tracker.csv")
    
    print(f"\n📁 Saved in:")
    print(f"  - {custom_path}")
    
    print(f"\n📊 File Details:")
    print(f"  - Shape: {df_custom.shape[0]} rows × {df_custom.shape[1]} columns")
    print(f"  - Rows: {len(df_custom)} (current + previous period)")
    if custom_start and custom_end:
        print(f"  - Current Period: {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')}")
        print(f"  - Previous Period: {prev_start.strftime('%m/%d/%Y')} - {prev_end.strftime('%m/%d/%Y')}")
        print(f"  - Duration: {(custom_end - custom_start).days + 1} days each")
    
    print(f"\n📈 Columns:")
    print(f"  - Date Range")
    print(f"  - Sched. calls, Live calls, Offers, Close 1")
    print(f"  - Show %, Offer %, Offer to Close %, Call to Close %")
    
    print("\n" + "="*70)
else:
    print("\n⚠️ Custom analysis not saved - no data to save")
    print("   Check date range and data availability")

======================================================================
CUSTOM DATE RANGE ANALYSIS - COMPLETE
======================================================================

✅ OUTPUT CREATED:
  - custom_sales_tracker.csv

📁 Saved in:
  - ../outputs/sales_tracker/custom_sales_tracker.csv

📊 File Details:
  - Shape: 2 rows × 9 columns
  - Rows: 2 (current + previous period)
  - Current Period: 11/01/2025 - 11/28/2025
  - Previous Period: 10/01/2025 - 10/28/2025
  - Duration: 28 days each

📈 Columns:
  - Date Range
  - Sched. calls, Live calls, Offers, Close 1
  - Show %, Offer %, Offer to Close %, Call to Close %

======================================================================

### Verification - Preview Custom Date Range File

In [26]:
if df_custom is not None and len(df_custom) > 0:
    print("Custom Date Range Sales Tracker Preview:")
    print("="*70)
    display(df_custom)
    
    print(f"\n✓ Custom date range analysis completed successfully!")
    print(f"  File location: ../outputs/sales_tracker/custom_sales_tracker.csv")
else:
    print("⚠️ No custom data available to preview")

Custom Date Range Sales Tracker Preview:
======================================================================

,Date Range,Sched. calls,Live calls,Offers,Close 1,Show %,Offer %,Offer to Close %,Call to Close %
0,11/01/2025 - 11/28/2025,493.00,338.00,207.00,67.00,56.09%,47.43%,23.5%,17.13%
1,10/01/2025 - 10/28/2025,408.00,306.00,200.00,65.00,70.65%,59.53%,19.97%,17.48%

✓ Custom date range analysis completed successfully!
  File location: ../outputs/sales_tracker/custom_sales_tracker.csv