# TYPEFORM SUBMISSIONS

###  Import Libraries

In [1]:
# Import required libraries
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os
import warnings
warnings.filterwarnings('ignore')

# Display settings for better visibility
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.float_format', lambda x: f'{x:.2f}')

print("✓ Libraries imported successfully")

✓ Libraries imported successfully

### Load Raw Data

In [2]:
# Load the raw Typeform submissions data
data_path = '../data/typeform_submissions.csv'

# Check if file exists
if not os.path.exists(data_path):
    print(f"❌ Error: File not found at {data_path}")
    print("Please make sure the file exists in the data folder.")
else:
    # Read the CSV file
    df_raw = pd.read_csv(data_path)
    
    print("✓ Typeform Submissions data loaded successfully")
    print(f"\nDataset shape: {df_raw.shape[0]} rows × {df_raw.shape[1]} columns")
    
    # Display only key columns to avoid wide display
    print(f"\nFirst few rows (key columns only):")
    key_columns = ['Start Date', 'Response Type', 'Email', 'First name', 'Last name']
    available_key_columns = [col for col in key_columns if col in df_raw.columns]
    
    if available_key_columns:
        display(df_raw[available_key_columns].head(10))
    else:
        # If key columns not found, just show first 5 columns
        display(df_raw.iloc[:, :5].head(10))

✓ Typeform Submissions data loaded successfully

Dataset shape: 992 rows × 32 columns

First few rows (key columns only):

  Response Type                                Email First name     Last name
0     completed                  steverf78@gmail.com      steve        fenech
1       partial          castelliverygroup@gmail.com        Roy       Kennedy
2     completed             visionzero2050@gmail.com     Samuel        Thenor
3     completed            ballard6910@sbcglobal.net    Gregory       Ballard
4     completed              ibroguy198927@yahoo.com    Ibrahim      Olanipun
5       started                                  NaN        NaN           NaN
6     completed                 ashkolhile@gmail.com     Ashkol  Hailegiorgis
7     completed                   ajrounds@gmail.com         AJ        Rounds
8     completed  mpactmanagementconsulting@gmail.com       Essi         Kwabi
9     completed                 mfatayergi@yahoo.com    Michael             F

### Inspect Data Structure

In [3]:
# Check if df_raw exists, if not, reload the data
try:
    df_raw.head()
except NameError:
    print("⚠️ df_raw not found. Loading data...")
    data_path = '../data/typeform_submissions.csv'
    df_raw = pd.read_csv(data_path)
    print("✓ Data loaded successfully")

# Display data info
print("Typeform Submissions Data Information:")
print("=" * 60)
df_raw.info()

print("\n" + "=" * 60)
print("Column Names:")
print("=" * 60)
for i, col in enumerate(df_raw.columns, 1):
    print(f"{i}. {col}")

print("\n" + "=" * 60)
print("Missing Values Check:")
print("=" * 60)
missing = df_raw.isnull().sum()
if missing.sum() == 0:
    print("✓ No missing values found")
else:
    print(missing[missing > 0])

print("\n" + "=" * 60)
print("Response Type Distribution:")
print("=" * 60)
if 'Response Type' in df_raw.columns:
    print(df_raw['Response Type'].value_counts())
else:
    print("Response Type column not found")

print("\n" + "=" * 60)
print("Sample Data Preview (key columns only):")
print("=" * 60)
# Display only key columns to avoid wide display
key_columns = ['Start Date', 'Response Type', 'Email', 'First name', 'Last name']
available_key_columns = [col for col in key_columns if col in df_raw.columns]

if available_key_columns:
    display(df_raw[available_key_columns].head(10))
else:
    # If key columns not found, just show first 5 columns
    display(df_raw.iloc[:, :5].head(10))

Typeform Submissions Data Information:
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 992 entries, 0 to 991
Data columns (total 32 columns):
 #   Column                                                                                                                                                                                                                                                                                                                                                                   Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                                                                                                   --------------  -----
 0   First name                                                                                                                                                                                                                                                                                                                                                               828 non-null    object
 1   Last name                                                                                                                                                                                                                                                                                                                                                                828 non-null    object
 2   Phone number                                                                                                                                                                                                                                                                                                                                                             828 non-null    float64
 3   Email                                                                                                                                                                                                                                                                                                                                                                    828 non-null    object
 4   *What‚Äôs the furthest you‚Äôve gotten in your business-buying journey?*                                                                                                                                                                                                                                                                                                 605 non-null    object
 5   *How long have you been actively searching for a business to buy?*                                                                                                                                                                                                                                                                                                       605 non-null    object
 6   *Tell us about your work experience*                                                                                                                                                                                                                                                                                                                                     608 non-null    object
 7   Sourcing high-quality deal flow                                                                                                                                                                                                                                                                                                                                          486 non-null    object
 8   Assessing and valuing opportunities                                                                                                                                                                                                                                                                                                                                      378 non-null    object
 9   Structuring and negotiating offers                                                                                                                                                                                                                                                                                                                                       302 non-null    object
 10  Securing financing and capital                                                                                                                                                                                                                                                                                                                                           299 non-null    object
 11  Navigating due diligence                                                                                                                                                                                                                                                                                                                                                 263 non-null    object
 12  Operating and growing the business post-acquisition                                                                                                                                                                                                                                                                                                                      189 non-null    object
 13  *What‚Äôs prompting you to seek support from our team now?*                                                                                                                                                                                                                                                                                                              609 non-null    object
 14  *What's your familiarity with SMB Deal Hunter?*                                                                                                                                                                                                                                                                                                                          605 non-null    object
 15  *How much time can you dedicate to your business acquisition search?*                                                                                                                                                                                                                                                                                                    605 non-null    object
 16  *How much money do you have to invest as a down payment to buy a business?*                                                                                                                                                                                                                                                                                              609 non-null    object
 17  *Aside from your down payment, can you tap into additional funds if you need to? (this could be home equity line of credit, stocks, 401(K), investors, etc.) Please share: *                                                                                                                                                                                             606 non-null    object
 18  *Are you a US citizen or green card holder?*                                                                                                                                                                                                                                                                                                                             609 non-null    float64
 19  *What types of businesses and industries are you interested in?*                                                                                                                                                                                                                                                                                                         609 non-null    object
 20  *How soon are you looking to get started working together 1:1 with me and my team in a structured program?*                                                                                                                                                                                                                                                              609 non-null    object
 21  *If you were to buy a business in the next 6‚Äì12 months, what level of annual income would make it worthwhile for you (or replace your current income)?*                                                                                                                                                                                                                605 non-null    object
 22  *Are there any specific questions you have that you want addressed on this call?*                                                                                                                                                                                                                                                                                        590 non-null    object
 23  Please book a discovery call                                                                                                                                                                                                                                                                                                                                             489 non-null    object
 24  Please book an intro call                                                                                                                                                                                                                                                                                                                                                119 non-null    object
 25  This is an application to see if you qualify to work with Helen Guo and the SMB Deal Hunter team to help you buy a business through our Pro program. If you're qualified, you'll be_ _able to book an interview.

 *Do not apply *if you are looking for general information about SMBs or do not know if buying a business is the path for you.

 Do you understand?  5 non-null      object
 26  Response Type                                                                                                                                                                                                                                                                                                                                                            992 non-null    object
 27  Start Date (UTC)                                                                                                                                                                                                                                                                                                                                                         992 non-null    object
 28  Stage Date (UTC)                                                                                                                                                                                                                                                                                                                                                         224 non-null    object
 29  Submit Date (UTC)                                                                                                                                                                                                                                                                                                                                                        609 non-null    object
 30  Tags                                                                                                                                                                                                                                                                                                                                                                     0 non-null      float64
 31  Ending                                                                                                                                                                                                                                                                                                                                                                   609 non-null    object
dtypes: float64(3), object(29)
memory usage: 248.1+ KB

============================================================
Column Names:
============================================================
1. First name
2. Last name
3. Phone number
4. Email
5. *What‚Äôs the furthest you‚Äôve gotten in your business-buying journey?*
6. *How long have you been actively searching for a business to buy?*
7. *Tell us about your work experience*
8. Sourcing high-quality deal flow
9. Assessing and valuing opportunities
10. Structuring and negotiating offers
11. Securing financing and capital
12. Navigating due diligence
13. Operating and growing the business post-acquisition
14. *What‚Äôs prompting you to seek support from our team now?*
15. *What's your familiarity with SMB Deal Hunter?*
16. *How much time can you dedicate to your business acquisition search?*
17. *How much money do you have to invest as a down payment to buy a business?*
18. *Aside from your down payment, can you tap into additional funds if you need to? (this could be home equity line of credit, stocks, 401(K), investors, etc.) Please share: *
19. *Are you a US citizen or green card holder?*
20. *What types of businesses and industries are you interested in?*
21. *How soon are you looking to get started working together 1:1 with me and my team in a structured program?*
22. *If you were to buy a business in the next 6‚Äì12 months, what level of annual income would make it worthwhile for you (or replace your current income)?*
23. *Are there any specific questions you have that you want addressed on this call?*
24. Please book a discovery call
25. Please book an intro call
26. This is an application to see if you qualify to work with Helen Guo and the SMB Deal Hunter team to help you buy a business through our Pro program. If you're qualified, you'll be_ _able to book an interview.

 *Do not apply *if you are looking for general information about SMBs or do not know if buying a business is the path for you.

 Do you understand?
27. Response Type
28. Start Date (UTC)
29. Stage Date (UTC)
30. Submit Date (UTC)
31. Tags
32. Ending

============================================================
Missing Values Check:
============================================================
First name                                                                                                                                                                                                                                                                                                                                                                     164
Last name                                                                                                                                                                                                                                                                                                                                                                      164
Phone number                                                                                                                                                                                                                                                                                                                                                                   164
Email                                                                                                                                                                                                                                                                                                                                                                          164
*What‚Äôs the furthest you‚Äôve gotten in your business-buying journey?*                                                                                                                                                                                                                                                                                                       387
*How long have you been actively searching for a business to buy?*                                                                                                                                                                                                                                                                                                             387
*Tell us about your work experience*                                                                                                                                                                                                                                                                                                                                           384
Sourcing high-quality deal flow                                                                                                                                                                                                                                                                                                                                                506
Assessing and valuing opportunities                                                                                                                                                                                                                                                                                                                                            614
Structuring and negotiating offers                                                                                                                                                                                                                                                                                                                                             690
Securing financing and capital                                                                                                                                                                                                                                                                                                                                                 693

  Response Type                                Email First name     Last name
0     completed                  steverf78@gmail.com      steve        fenech
1       partial          castelliverygroup@gmail.com        Roy       Kennedy
2     completed             visionzero2050@gmail.com     Samuel        Thenor
3     completed            ballard6910@sbcglobal.net    Gregory       Ballard
4     completed              ibroguy198927@yahoo.com    Ibrahim      Olanipun
5       started                                  NaN        NaN           NaN
6     completed                 ashkolhile@gmail.com     Ashkol  Hailegiorgis
7     completed                   ajrounds@gmail.com         AJ        Rounds
8     completed  mpactmanagementconsulting@gmail.com       Essi         Kwabi
9     completed                 mfatayergi@yahoo.com    Michael             F

### Clean Raw Data - Remove Blank Emails

In [4]:
# Create a working copy
df_clean = df_raw.copy()

print(f"Initial dataset: {len(df_clean)} rows")

# Check for blank/null emails
blank_emails = df_clean['Email'].isna() | (df_clean['Email'].astype(str).str.strip() == '')
blank_count = blank_emails.sum()

if blank_count > 0:
    print(f"\n⚠️ Found {blank_count} rows with blank Email")
    print("Rows to be removed (showing key columns only):")
    
    # Display only key columns to avoid wide output
    key_columns = ['Start Date', 'Response Type', 'Email']
    available_key_columns = [col for col in key_columns if col in df_clean.columns]
    
    if available_key_columns:
        display(df_clean[blank_emails][available_key_columns].head(10))
    else:
        display(df_clean[blank_emails].iloc[:, :5].head(10))
    
    # Remove rows with blank emails
    df_clean = df_clean[~blank_emails].copy()
    print(f"✓ Removed {blank_count} rows with blank Email")
else:
    print("\n✓ No blank emails found")

print(f"\nDataset after removing blank emails: {len(df_clean)} rows")

Initial dataset: 992 rows

⚠️ Found 164 rows with blank Email
Rows to be removed (showing key columns only):

   Response Type Email
5        started   NaN
11       started   NaN
16       started   NaN
20       started   NaN
26       started   NaN
51       started   NaN
54       started   NaN
56       started   NaN
64       started   NaN
66       started   NaN

✓ Removed 164 rows with blank Email

Dataset after removing blank emails: 828 rows

### Clean Duplicates Based on Email - Step 1 (Identify Discovery/Intro Call Types)

In [5]:
# Identify which rows are for Discovery Calls and which are for Intro Calls
# Based on whether there's a link in the respective columns

# CRITICAL: Normalize email to lowercase FIRST
df_clean['Email'] = df_clean['Email'].str.lower().str.strip()

# First, identify the Start Date column
start_date_col = None
for col in df_clean.columns:
    if 'start' in col.lower() and 'date' in col.lower():
        start_date_col = col
        break

if start_date_col is None:
    for col in df_clean.columns:
        if 'date' in col.lower() and 'utc' in col.lower():
            start_date_col = col
            break

print(f"✓ Start Date column identified: '{start_date_col}'")

# Check column names for discovery and intro call columns
discovery_col = None
intro_col = None

for col in df_clean.columns:
    if 'discovery' in col.lower() and 'book' in col.lower():
        discovery_col = col
    if 'intro' in col.lower() and 'book' in col.lower():
        intro_col = col

print(f"Discovery Call Column: {discovery_col}")
print(f"Intro Call Column: {intro_col}")

# Add helper columns to identify call type
if discovery_col and intro_col:
    # A row is for Discovery Call if there's a non-empty value in the discovery column
    df_clean['Is_Discovery_Call'] = df_clean[discovery_col].notna() & (df_clean[discovery_col].astype(str).str.strip() != '')
    
    # A row is for Intro Call if there's a non-empty value in the intro column
    df_clean['Is_Intro_Call'] = df_clean[intro_col].notna() & (df_clean[intro_col].astype(str).str.strip() != '')
    
    print("\n✓ Call type identification complete")
    print(f"Discovery Calls: {df_clean['Is_Discovery_Call'].sum()}")
    print(f"Intro Calls: {df_clean['Is_Intro_Call'].sum()}")
else:
    print("\n⚠️ Warning: Could not find discovery/intro call columns")
    df_clean['Is_Discovery_Call'] = False
    df_clean['Is_Intro_Call'] = False

✓ Start Date column identified: 'Start Date (UTC)'
Discovery Call Column: Please book a discovery call
Intro Call Column: Please book an intro call

✓ Call type identification complete
Discovery Calls: 487
Intro Calls: 118

### Clean Duplicates Based on Email - Step 2 (Process Duplicates)

In [6]:
# Re-identify the Start Date column if not already in memory
try:
    start_date_col
    print(f"✓ Using existing start_date_col: {start_date_col}")
except NameError:
    # Find the Start Date column
    start_date_col = None
    print(f"Available columns: {df_clean.columns.tolist()}")
    
    # First try to find "Start Date"
    for col in df_clean.columns:
        if 'start' in col.lower() and 'date' in col.lower():
            start_date_col = col
            break
    
    # If not found, look for any column with "date" and "utc"
    if start_date_col is None:
        for col in df_clean.columns:
            if 'date' in col.lower() and 'utc' in col.lower():
                start_date_col = col
                break
    
    print(f"✓ Identified Start Date column: {start_date_col}")

if start_date_col is None:
    raise ValueError("Could not find Start Date column!")

# Convert Start Date to datetime for comparison
df_clean[start_date_col] = pd.to_datetime(df_clean[start_date_col], format='mixed', errors='coerce')

# Sort by Email, Response Type (completed comes before partial alphabetically), and Start Date (latest first)
df_clean = df_clean.sort_values(
    by=['Email', 'Response Type', start_date_col],
    ascending=[True, True, False]
).reset_index(drop=True)

# Group by Email to process duplicates
email_groups = df_clean.groupby('Email')

rows_to_keep = []
duplicate_removal_log = []

for email, group in email_groups:
    if len(group) == 1:
        # Only one entry for this email, keep it
        rows_to_keep.append(group.index[0])
    else:
        # Multiple entries for this email
        partials = group[group['Response Type'] == 'partial']
        completed = group[group['Response Type'] == 'completed']
        
        # Rule 1: If we have ANY completed, remove ALL partials for this email
        if len(completed) > 0:
            # Log removal of partials
            if len(partials) > 0:
                duplicate_removal_log.append({
                    'Email': email,
                    'Rule': 'Remove ALL Partials (Completed exists)',
                    'Removed Partials': len(partials),
                    'Kept Completed': len(completed)
                })
            
            # Now process the completed entries
            if len(completed) == 1:
                # Only 1 completed, keep it
                rows_to_keep.append(completed.index[0])
            elif len(completed) >= 2:
                # Multiple completed - check call types
                discovery_completed = completed[completed['Is_Discovery_Call'] == True]
                intro_completed = completed[completed['Is_Intro_Call'] == True]
                
                # If we have both discovery and intro, keep one of each (latest of each type)
                if len(discovery_completed) > 0 and len(intro_completed) > 0:
                    # Keep the latest discovery call
                    latest_discovery = discovery_completed.iloc[0]
                    rows_to_keep.append(latest_discovery.name)
                    
                    # Keep the latest intro call
                    latest_intro = intro_completed.iloc[0]
                    rows_to_keep.append(latest_intro.name)
                    
                    duplicate_removal_log.append({
                        'Email': email,
                        'Rule': 'Keep both Discovery and Intro Completed',
                        'Removed Partials': len(partials),
                        'Kept Completed': 2
                    })
                else:
                    # All completed are same type, keep only the latest
                    latest_completed = completed.iloc[0]
                    duplicate_removal_log.append({
                        'Email': email,
                        'Rule': 'Keep latest Completed (same type)',
                        'Removed Partials': len(partials),
                        'Kept Completed': 1
                    })
                    rows_to_keep.append(latest_completed.name)
        
        # Rule 2: If we have ONLY partials (no completed), keep the latest partial
        else:
            if len(partials) >= 2:
                latest_partial = partials.iloc[0]  # Already sorted by date descending
                duplicate_removal_log.append({
                    'Email': email,
                    'Rule': 'Keep latest Partial (no Completed)',
                    'Removed Partials': len(partials) - 1,
                    'Kept Completed': 0
                })
                rows_to_keep.append(latest_partial.name)
            elif len(partials) == 1:
                # Only 1 partial, keep it
                rows_to_keep.append(partials.index[0])

# Create cleaned dataframe
df_cleaned = df_clean.loc[rows_to_keep].copy()

# Display duplicate removal summary
print("\n" + "=" * 60)
print("DUPLICATE REMOVAL SUMMARY")
print("=" * 60)
print(f"Rows before duplicate removal: {len(df_clean)}")
print(f"Rows after duplicate removal: {len(df_cleaned)}")
print(f"Total rows removed: {len(df_clean) - len(df_cleaned)}")

if duplicate_removal_log:
    print("\nDuplicate Removal Log (first 20 entries):")
    df_log = pd.DataFrame(duplicate_removal_log)
    display(df_log.head(20))
    print(f"\nTotal duplicate groups processed: {len(df_log)}")
else:
    print("\n✓ No duplicates found")

# Verify Response Type counts
print("\nResponse Type counts in cleaned data:")
print(df_cleaned['Response Type'].value_counts())

print("=" * 60)

✓ Using existing start_date_col: Start Date (UTC)

============================================================
DUPLICATE REMOVAL SUMMARY
============================================================
Rows before duplicate removal: 828
Rows after duplicate removal: 755
Total rows removed: 73

Duplicate Removal Log (first 20 entries):

,Email,Rule,Removed Partials,Kept Completed
0,abdulla777999000@gmail.com,Remove ALL Partials (Completed exists),1,1
1,ananthcherukupally@gmail.com,Remove ALL Partials (Completed exists),2,1
2,ankur.rice@gmail.com,Remove ALL Partials (Completed exists),1,1
3,anthony.annunziata@gmail.com,Remove ALL Partials (Completed exists),3,1
4,at@f3aholdingsllc.com,Keep latest Partial (no Completed),1,0
5,athinesh@gmail.com,Remove ALL Partials (Completed exists),1,1
6,atintl@aol.com,Remove ALL Partials (Completed exists),1,1
7,austin.j.king250@gmail.com,Remove ALL Partials (Completed exists),1,1
8,benjaminrowbotham@gmail.com,Remove ALL Partials (Completed exists),1,1
9,brigham.vanauken@gmail.com,Keep latest Partial (no Completed),1,0
10,cdgaluskin@gmail.com,Remove ALL Partials (Completed exists),1,1
11,chanceawelton@gmail.com,Keep latest Partial (no Completed),1,0
12,chenanthony21@gmail.com,Remove ALL Partials (Completed exists),3,1
13,derrestwilliams@gmail.com,Keep latest Completed (same type),0,1
14,dkcstone@gmail.com,Keep latest Partial (no Completed),1,0
15,g60madden@gmail.com,Remove ALL Partials (Completed exists),1,1
16,gegeogundu@gmail.com,Keep latest Completed (same type),0,1
17,hadi.soueidan9@gmail.com,Remove ALL Partials (Completed exists),1,1
18,jamesgillis123@att.net,Keep latest Partial (no Completed),2,0
19,jay@smbdealhunter.xyz,Keep latest Completed (same type),0,1

Total duplicate groups processed: 58

Response Type counts in cleaned data:
Response Type
completed    592
partial      163
Name: count, dtype: int64
============================================================

### Save Cleaned Raw Data

In [7]:
# Create output directory
output_dir = '../outputs/typeform_submissions'
os.makedirs(output_dir, exist_ok=True)

# Save cleaned raw data
cleaned_raw_path = os.path.join(output_dir, 'cleaned_raw_typeform_submissions.csv')
df_cleaned.to_csv(cleaned_raw_path, index=False)

print(f"✓ Cleaned raw data saved to: {cleaned_raw_path}")
print(f"  Shape: {df_cleaned.shape[0]} rows × {df_cleaned.shape[1]} columns")

✓ Cleaned raw data saved to: ../outputs/typeform_submissions/cleaned_raw_typeform_submissions.csv
  Shape: 755 rows × 34 columns

### Create Daily Aggregated Data

In [8]:
# Work with cleaned data
df_daily_prep = df_cleaned.copy()

print(f"✓ Using '{start_date_col}' column for date aggregation")
print(f"Total rows in cleaned data: {len(df_daily_prep)}")

# Convert Start Date to date only (extract date from the UTC timestamp)
df_daily_prep['AggregationDate'] = pd.to_datetime(df_daily_prep[start_date_col]).dt.date

# Identify discovery and intro call columns
discovery_col = None
intro_col = None

for col in df_daily_prep.columns:
    if 'discovery' in col.lower() and 'book' in col.lower():
        discovery_col = col
        print(f"✓ Found Discovery Call Column: {discovery_col}")
    if 'intro' in col.lower() and 'book' in col.lower():
        intro_col = col
        print(f"✓ Found Intro Call Column: {intro_col}")

# Group by AggregationDate and count each response type separately
df_daily_counts = df_daily_prep.groupby(['AggregationDate', 'Response Type']).size().unstack(fill_value=0).reset_index()

# Rename columns (response types are lowercase in the data)
if 'partial' in df_daily_counts.columns:
    df_daily_counts.rename(columns={'partial': 'Partials'}, inplace=True)
else:
    df_daily_counts['Partials'] = 0

if 'completed' in df_daily_counts.columns:
    df_daily_counts.rename(columns={'completed': 'Completed'}, inplace=True)
else:
    df_daily_counts['Completed'] = 0

# Aggregate Discovery and Intro Calls by date (count non-empty values)
if discovery_col:
    discovery_counts = df_daily_prep[df_daily_prep[discovery_col].notna() & (df_daily_prep[discovery_col].astype(str).str.strip() != '')].groupby('AggregationDate').size().reset_index(name='Discovery Calls')
else:
    discovery_counts = None

if intro_col:
    intro_counts = df_daily_prep[df_daily_prep[intro_col].notna() & (df_daily_prep[intro_col].astype(str).str.strip() != '')].groupby('AggregationDate').size().reset_index(name='Intro Calls')
else:
    intro_counts = None

# Merge all counts
df_daily = df_daily_counts[['AggregationDate', 'Partials', 'Completed']].copy()

if discovery_counts is not None:
    df_daily = df_daily.merge(discovery_counts, on='AggregationDate', how='left')
    df_daily['Discovery Calls'] = df_daily['Discovery Calls'].fillna(0).astype(int)
else:
    df_daily['Discovery Calls'] = 0

if intro_counts is not None:
    df_daily = df_daily.merge(intro_counts, on='AggregationDate', how='left')
    df_daily['Intro Calls'] = df_daily['Intro Calls'].fillna(0).astype(int)
else:
    df_daily['Intro Calls'] = 0

# Rename AggregationDate to Date
df_daily.rename(columns={'AggregationDate': 'Date'}, inplace=True)

# Reorder columns
df_daily = df_daily[['Date', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']]

# Sort by date
df_daily = df_daily.sort_values('Date').reset_index(drop=True)

# Convert Date to datetime then format as MM/DD/YYYY
df_daily['Date'] = pd.to_datetime(df_daily['Date']).dt.strftime('%m/%d/%Y')

print("\n✓ Daily data aggregated successfully")
print(f"\nDaily dataset shape: {df_daily.shape[0]} rows × {df_daily.shape[1]} columns")
print(f"\nFirst 5 days:")
display(df_daily.head(5))

print(f"\nLast 5 days:")
display(df_daily.tail(5))

# Verification summary
print(f"\n" + "=" * 60)
print("DAILY AGGREGATION VERIFICATION")
print("=" * 60)
print(f"Total Partials: {df_daily['Partials'].sum()}")
print(f"Total Completed: {df_daily['Completed'].sum()}")
print(f"Total Discovery Calls: {df_daily['Discovery Calls'].sum()}")
print(f"Total Intro Calls: {df_daily['Intro Calls'].sum()}")
print(f"Total Submissions: {df_daily['Partials'].sum() + df_daily['Completed'].sum()}")
print("=" * 60)

✓ Using 'Start Date (UTC)' column for date aggregation
Total rows in cleaned data: 755
✓ Found Discovery Call Column: Please book a discovery call
✓ Found Intro Call Column: Please book an intro call

✓ Daily data aggregated successfully

Daily dataset shape: 36 rows × 5 columns

First 5 days:

         Date  Partials  Completed  Discovery Calls  Intro Calls
0  10/03/2025         1          6                5            1
1  10/04/2025         3         12               10            2
2  10/05/2025         5         15               10            5
3  10/06/2025         8         24               19            5
4  10/07/2025         7         21               17            4

Last 5 days:

          Date  Partials  Completed  Discovery Calls  Intro Calls
31  11/03/2025         7         27               19            8
32  11/04/2025         5         35               29            6
33  11/05/2025         6         33               29            4
34  11/06/2025         7         28               26            2
35  11/07/2025         1          8                7            1

============================================================
DAILY AGGREGATION VERIFICATION
============================================================
Total Partials: 163
Total Completed: 592
Total Discovery Calls: 476
Total Intro Calls: 116
Total Submissions: 755
============================================================

### Create Weekly Aggregated Data

In [9]:
# Work with daily data
df_weekly_prep = df_daily.copy()

# Convert Date to datetime
df_weekly_prep['Date'] = pd.to_datetime(df_weekly_prep['Date'])

# Create week identifier (week starting on Sunday)
# Sunday = 6 in dayofweek, we want Sunday to map to the start of its week
# Formula: subtract (dayofweek + 1) % 7 days
df_weekly_prep['Week'] = df_weekly_prep['Date'] - pd.to_timedelta((df_weekly_prep['Date'].dt.dayofweek + 1) % 7, unit='D')

# Aggregate by week
df_weekly = df_weekly_prep.groupby('Week').agg({
    'Date': ['min', 'max'],
    'Partials': 'sum',
    'Completed': 'sum',
    'Discovery Calls': 'sum',
    'Intro Calls': 'sum'
}).reset_index()

# Flatten column names
df_weekly.columns = ['Week', 'Week_Start', 'Week_End', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']

# Create Week Number (sequential)
df_weekly['Week_Num'] = range(1, len(df_weekly) + 1)

# Format date range
df_weekly['Date Range'] = (df_weekly['Week_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                           df_weekly['Week_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns
df_weekly = df_weekly[['Week_Num', 'Date Range', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']]

# Rename Week_Num to Week
df_weekly.columns = ['Week', 'Date Range', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']

print("✓ Weekly data aggregated successfully")
print(f"\nWeekly dataset shape: {df_weekly.shape[0]} rows × {df_weekly.shape[1]} columns")
print(f"\nFirst 5 weeks:")
display(df_weekly.head(5))

print(f"\nLast 5 weeks:")
display(df_weekly.tail(5))

✓ Weekly data aggregated successfully

Weekly dataset shape: 6 rows × 6 columns

First 5 weeks:

,Week,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,1,10/03/2025 - 10/04/2025,4,18,15,3
1,2,10/05/2025 - 10/11/2025,32,103,77,26
2,3,10/12/2025 - 10/18/2025,21,108,81,27
3,4,10/19/2025 - 10/25/2025,36,104,81,23
4,5,10/26/2025 - 11/01/2025,36,124,109,15

Last 5 weeks:

,Week,Date Range,Partials,Completed,Discovery Calls,Intro Calls
1,2,10/05/2025 - 10/11/2025,32,103,77,26
2,3,10/12/2025 - 10/18/2025,21,108,81,27
3,4,10/19/2025 - 10/25/2025,36,104,81,23
4,5,10/26/2025 - 11/01/2025,36,124,109,15
5,6,11/02/2025 - 11/07/2025,34,135,113,22

### Create Monthly Aggregated Data

In [10]:
# Work with daily data
df_monthly_prep = df_daily.copy()

# Convert Date to datetime
df_monthly_prep['Date'] = pd.to_datetime(df_monthly_prep['Date'])

# Extract year and month
df_monthly_prep['Year'] = df_monthly_prep['Date'].dt.year
df_monthly_prep['Month_Num'] = df_monthly_prep['Date'].dt.month
df_monthly_prep['Month_Name'] = df_monthly_prep['Date'].dt.strftime('%B')

# Create month identifier for grouping
df_monthly_prep['YearMonth'] = df_monthly_prep['Date'].dt.to_period('M')

# Aggregate by month
df_monthly = df_monthly_prep.groupby('YearMonth').agg({
    'Date': ['min', 'max'],
    'Month_Name': 'first',
    'Year': 'first',
    'Partials': 'sum',
    'Completed': 'sum',
    'Discovery Calls': 'sum',
    'Intro Calls': 'sum'
}).reset_index()

# Flatten column names
df_monthly.columns = ['YearMonth', 'Month_Start', 'Month_End', 'Month_Name', 'Year',
                      'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']

# Create Month label (e.g., "January 2025")
df_monthly['Month'] = df_monthly['Month_Name'] + ' ' + df_monthly['Year'].astype(str)

# Create Date Range
df_monthly['Date Range'] = (df_monthly['Month_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                            df_monthly['Month_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns
df_monthly = df_monthly[['Month', 'Date Range', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']]

print("✓ Monthly data aggregated successfully")
print(f"\nMonthly dataset shape: {df_monthly.shape[0]} rows × {df_monthly.shape[1]} columns")
print(f"\nAll months:")
display(df_monthly)

✓ Monthly data aggregated successfully

Monthly dataset shape: 2 rows × 6 columns

All months:

,Month,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,October 2025,10/03/2025 - 10/31/2025,126,446,353,93
1,November 2025,11/01/2025 - 11/07/2025,37,146,123,23

### Create Quarterly Aggregated Data

In [11]:
# Work with daily data
df_quarterly_prep = df_daily.copy()

# Convert Date to datetime
df_quarterly_prep['Date'] = pd.to_datetime(df_quarterly_prep['Date'])

# Extract year and quarter
df_quarterly_prep['Year'] = df_quarterly_prep['Date'].dt.year
df_quarterly_prep['Quarter_Num'] = df_quarterly_prep['Date'].dt.quarter

# Create quarter identifier for grouping
df_quarterly_prep['YearQuarter'] = (df_quarterly_prep['Year'].astype(str) + 'Q' + 
                                    df_quarterly_prep['Quarter_Num'].astype(str))

# Aggregate by quarter
df_quarterly = df_quarterly_prep.groupby('YearQuarter').agg({
    'Date': ['min', 'max'],
    'Partials': 'sum',
    'Completed': 'sum',
    'Discovery Calls': 'sum',
    'Intro Calls': 'sum'
}).reset_index()

# Flatten column names
df_quarterly.columns = ['Quarter', 'Quarter_Start', 'Quarter_End',
                        'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']

# Create Date Range
df_quarterly['Date Range'] = (df_quarterly['Quarter_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                              df_quarterly['Quarter_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns
df_quarterly = df_quarterly[['Quarter', 'Date Range', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']]

print("✓ Quarterly data aggregated successfully")
print(f"\nQuarterly dataset shape: {df_quarterly.shape[0]} rows × {df_quarterly.shape[1]} columns")
print(f"\nAll quarters:")
display(df_quarterly)

✓ Quarterly data aggregated successfully

Quarterly dataset shape: 1 rows × 6 columns

All quarters:

,Quarter,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,2025Q4,10/03/2025 - 11/07/2025,163,592,476,116

### Create Annual Aggregated Data

In [12]:
# Work with daily data
df_annual_prep = df_daily.copy()

# Convert Date to datetime
df_annual_prep['Date'] = pd.to_datetime(df_annual_prep['Date'])

# Extract year
df_annual_prep['Year'] = df_annual_prep['Date'].dt.year

# Aggregate by year
df_annual = df_annual_prep.groupby('Year').agg({
    'Date': ['min', 'max'],
    'Partials': 'sum',
    'Completed': 'sum',
    'Discovery Calls': 'sum',
    'Intro Calls': 'sum'
}).reset_index()

# Flatten column names
df_annual.columns = ['Year', 'Year_Start', 'Year_End',
                     'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']

# Create Date Range
df_annual['Date Range'] = (df_annual['Year_Start'].dt.strftime('%m/%d/%Y') + ' - ' + 
                           df_annual['Year_End'].dt.strftime('%m/%d/%Y'))

# Select and reorder columns
df_annual = df_annual[['Year', 'Date Range', 'Partials', 'Completed', 'Discovery Calls', 'Intro Calls']]

print("✓ Annual data aggregated successfully")
print(f"\nAnnual dataset shape: {df_annual.shape[0]} rows × {df_annual.shape[1]} columns")
print(f"\nAll years:")
display(df_annual)

✓ Annual data aggregated successfully

Annual dataset shape: 1 rows × 6 columns

All years:

,Year,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,2025,10/03/2025 - 11/07/2025,163,592,476,116

### Save All Datasets to CSV

In [13]:
# Output directory already created in Step 7
print("\n" + "=" * 60)
print("SAVING ALL DATASETS TO CSV")
print("=" * 60 + "\n")

# Save Daily data
daily_path = os.path.join(output_dir, 'daily_typeform_submissions.csv')
df_daily.to_csv(daily_path, index=False)
print(f"✓ Saved: {daily_path}")
print(f"  Shape: {df_daily.shape[0]} rows × {df_daily.shape[1]} columns\n")

# Save Weekly data
weekly_path = os.path.join(output_dir, 'weekly_typeform_submissions.csv')
df_weekly.to_csv(weekly_path, index=False)
print(f"✓ Saved: {weekly_path}")
print(f"  Shape: {df_weekly.shape[0]} rows × {df_weekly.shape[1]} columns\n")

# Save Monthly data
monthly_path = os.path.join(output_dir, 'monthly_typeform_submissions.csv')
df_monthly.to_csv(monthly_path, index=False)
print(f"✓ Saved: {monthly_path}")
print(f"  Shape: {df_monthly.shape[0]} rows × {df_monthly.shape[1]} columns\n")

# Save Quarterly data
quarterly_path = os.path.join(output_dir, 'quarterly_typeform_submissions.csv')
df_quarterly.to_csv(quarterly_path, index=False)
print(f"✓ Saved: {quarterly_path}")
print(f"  Shape: {df_quarterly.shape[0]} rows × {df_quarterly.shape[1]} columns\n")

# Save Annual data
annual_path = os.path.join(output_dir, 'annual_typeform_submissions.csv')
df_annual.to_csv(annual_path, index=False)
print(f"✓ Saved: {annual_path}")
print(f"  Shape: {df_annual.shape[0]} rows × {df_annual.shape[1]} columns\n")

print("=" * 60)
print("✓ All datasets saved successfully!")
print("=" * 60)

============================================================
SAVING ALL DATASETS TO CSV
============================================================

✓ Saved: ../outputs/typeform_submissions/daily_typeform_submissions.csv
  Shape: 36 rows × 5 columns

✓ Saved: ../outputs/typeform_submissions/weekly_typeform_submissions.csv
  Shape: 6 rows × 6 columns

✓ Saved: ../outputs/typeform_submissions/monthly_typeform_submissions.csv
  Shape: 2 rows × 6 columns

✓ Saved: ../outputs/typeform_submissions/quarterly_typeform_submissions.csv
  Shape: 1 rows × 6 columns

✓ Saved: ../outputs/typeform_submissions/annual_typeform_submissions.csv
  Shape: 1 rows × 6 columns

============================================================
✓ All datasets saved successfully!
============================================================

### Verification - Preview Saved Files

In [14]:
# List all files in the output directory
print("\n" + "=" * 60)
print("FILES IN OUTPUT DIRECTORY")
print("=" * 60)
for file in sorted(os.listdir(output_dir)):
    file_path = os.path.join(output_dir, file)
    file_size = os.path.getsize(file_path) / 1024  # Size in KB
    print(f"  • {file:<45} ({file_size:.2f} KB)")

print("\n" + "=" * 60)
print("Preview of Daily Typeform Submissions (first 10 rows):")
print("=" * 60)
df_verify_daily = pd.read_csv(daily_path)
display(df_verify_daily.head(5))

print("\n" + "=" * 60)
print("Preview of Weekly Typeform Submissions (first 10 rows):")
print("=" * 60)
df_verify_weekly = pd.read_csv(weekly_path)
display(df_verify_weekly.head(5))

print("\n" + "=" * 60)
print("Preview of Monthly Typeform Submissions (all rows):")
print("=" * 60)
df_verify_monthly = pd.read_csv(monthly_path)
display(df_verify_monthly)

print("\n" + "=" * 60)
print("Preview of Quarterly Typeform Submissions (all rows):")
print("=" * 60)
df_verify_quarterly = pd.read_csv(quarterly_path)
display(df_verify_quarterly)

print("\n" + "=" * 60)
print("Preview of Annual Typeform Submissions (all rows):")
print("=" * 60)
df_verify_annual = pd.read_csv(annual_path)
display(df_verify_annual)

============================================================
FILES IN OUTPUT DIRECTORY
============================================================
  • annual_typeform_submissions.csv               (0.11 KB)
  • cleaned_raw_typeform_submissions.csv          (539.23 KB)
  • custom_typeform_submissions.csv               (0.13 KB)
  • daily_typeform_submissions.csv                (0.77 KB)
  • monthly_typeform_submissions.csv              (0.16 KB)
  • quarterly_typeform_submissions.csv            (0.11 KB)
  • weekly_typeform_submissions.csv               (0.29 KB)

============================================================
Preview of Daily Typeform Submissions (first 10 rows):
============================================================

         Date  Partials  Completed  Discovery Calls  Intro Calls
0  10/03/2025         1          6                5            1
1  10/04/2025         3         12               10            2
2  10/05/2025         5         15               10            5
3  10/06/2025         8         24               19            5
4  10/07/2025         7         21               17            4

============================================================
Preview of Weekly Typeform Submissions (first 10 rows):
============================================================

,Week,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,1,10/03/2025 - 10/04/2025,4,18,15,3
1,2,10/05/2025 - 10/11/2025,32,103,77,26
2,3,10/12/2025 - 10/18/2025,21,108,81,27
3,4,10/19/2025 - 10/25/2025,36,104,81,23
4,5,10/26/2025 - 11/01/2025,36,124,109,15

============================================================
Preview of Monthly Typeform Submissions (all rows):
============================================================

,Month,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,October 2025,10/03/2025 - 10/31/2025,126,446,353,93
1,November 2025,11/01/2025 - 11/07/2025,37,146,123,23

============================================================
Preview of Quarterly Typeform Submissions (all rows):
============================================================

,Quarter,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,2025Q4,10/03/2025 - 11/07/2025,163,592,476,116

============================================================
Preview of Annual Typeform Submissions (all rows):
============================================================

,Year,Date Range,Partials,Completed,Discovery Calls,Intro Calls
0,2025,10/03/2025 - 11/07/2025,163,592,476,116

### Summary Statistics

In [15]:
print("\n" + "=" * 70)
print("TYPEFORM SUBMISSIONS DATA PROCESSING SUMMARY")
print("=" * 70)

print(f"\n📊 Data Processing Summary:")
print(f"  Raw data rows: {len(df_raw)}")
print(f"  Rows removed (blank emails): {len(df_raw) - len(df_clean)}")
print(f"  Rows removed (duplicates): {len(df_clean) - len(df_cleaned)}")
print(f"  Final cleaned rows: {len(df_cleaned)}")

print(f"\n📈 Aggregated Datasets Created:")
print(f"  Daily records: {df_daily.shape[0]}")
print(f"  Weekly records: {df_weekly.shape[0]}")
print(f"  Monthly records: {df_monthly.shape[0]}")
print(f"  Quarterly records: {df_quarterly.shape[0]}")
print(f"  Annual records: {df_annual.shape[0]}")

print(f"\n💾 Files Saved:")
print(f"  Location: {output_dir}")
print(f"  Total files: 6 (1 cleaned raw + 5 aggregated)")

# Calculate overall metrics
total_partials = df_daily['Partials'].sum()
total_completed = df_daily['Completed'].sum()
total_discovery = df_daily['Discovery Calls'].sum()
total_intro = df_daily['Intro Calls'].sum()
total_submissions = total_partials + total_completed

print(f"\n📊 Overall Metrics:")
print(f"  Total Submissions: {total_submissions:,}")
print(f"  Total Partials: {total_partials:,} ({total_partials/total_submissions*100:.1f}%)")
print(f"  Total Completed: {total_completed:,} ({total_completed/total_submissions*100:.1f}%)")
print(f"  Total Discovery Calls: {total_discovery:,}")
print(f"  Total Intro Calls: {total_intro:,}")

print("\n" + "=" * 70)
print("✓ Typeform Submissions data processing complete!")
print("=" * 70)

======================================================================
TYPEFORM SUBMISSIONS DATA PROCESSING SUMMARY
======================================================================

📊 Data Processing Summary:
  Raw data rows: 992
  Rows removed (blank emails): 164
  Rows removed (duplicates): 73
  Final cleaned rows: 755

📈 Aggregated Datasets Created:
  Daily records: 36
  Weekly records: 6
  Monthly records: 2
  Quarterly records: 1
  Annual records: 1

💾 Files Saved:
  Location: ../outputs/typeform_submissions
  Total files: 6 (1 cleaned raw + 5 aggregated)

📊 Overall Metrics:
  Total Submissions: 755
  Total Partials: 163 (21.6%)
  Total Completed: 592 (78.4%)
  Total Discovery Calls: 476
  Total Intro Calls: 116

======================================================================
✓ Typeform Submissions data processing complete!
======================================================================

#

## CUSTOM DATE RANGE ANALYSIS

### Load Custom Date Range Parameters

In [16]:
# Load analysis reference dates from CSV
ref_dates_path = '../analysis_ref_date.csv'

# Check if file exists
if not os.path.exists(ref_dates_path):
    print(f"❌ Error: File not found at {ref_dates_path}")
    custom_start = None
    custom_end = None
else:
    # Load reference dates
    ref_dates = pd.read_csv(ref_dates_path, header=None)
    
    # Parse custom date range
    custom_start = None
    custom_end = None
    
    for idx, row in ref_dates.iterrows():
        if row[0] == 'Custom Start Date':
            try:
                custom_start = pd.to_datetime(row[1])
            except:
                custom_start = None
        elif row[0] == 'Custom End Date':
            try:
                custom_end = pd.to_datetime(row[1])
            except:
                custom_end = None
    
    print(f"Custom Date Range:")
    print(f"  Start: {custom_start if custom_start else 'Not specified'}")
    print(f"  End: {custom_end if custom_end else 'Not specified'}")
    
    if custom_start and custom_end:
        date_range_days = (custom_end - custom_start).days + 1
        print(f"  Duration: {date_range_days} days")
    else:
        print("\n⚠️ Custom date range not properly specified in analysis_ref_date.csv")

Custom Date Range:
  Start: 2025-11-01 00:00:00
  End: 2025-11-28 00:00:00
  Duration: 28 days

### Generate Custom Date Range Typeform Submissions Data

In [17]:
print("\n" + "="*70)
print("CUSTOM DATE RANGE TYPEFORM SUBMISSIONS AGGREGATION (WITH PREVIOUS PERIOD)")
print("="*70 + "\n")

if custom_start and custom_end:
    # Calculate previous period dates - shift back by ONE MONTH, keeping same day-of-month
    from dateutil.relativedelta import relativedelta
    
    prev_start = custom_start - relativedelta(months=1)
    prev_end = custom_end - relativedelta(months=1)
    
    # Calculate duration for display
    date_range_duration = (custom_end - custom_start).days + 1
    
    print(f"Current Period (Requested): {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')} ({date_range_duration} days)")
    print(f"Previous Period (Requested): {prev_start.strftime('%m/%d/%Y')} - {prev_end.strftime('%m/%d/%Y')} ({date_range_duration} days)\n")
    
    # Work with cleaned data for filtering
    df_custom_prep = df_cleaned.copy()
    
    # Convert Start Date to datetime
    df_custom_prep['AggregationDate'] = pd.to_datetime(df_custom_prep[start_date_col])
    
    # Filter data for CURRENT custom date range
    df_custom_filtered = df_custom_prep[
        (df_custom_prep['AggregationDate'] >= custom_start) & 
        (df_custom_prep['AggregationDate'] <= custom_end)
    ].copy()
    
    # Identify discovery and intro call columns (only once)
    discovery_col = None
    intro_col = None
    
    for col in df_custom_prep.columns:
        if 'discovery' in col.lower() and 'book' in col.lower():
            discovery_col = col
        if 'intro' in col.lower() and 'book' in col.lower():
            intro_col = col
    
    # Create empty list to store rows
    custom_rows = []
    
    # Process CURRENT period
    if len(df_custom_filtered) > 0:
        # Get ACTUAL start and end dates from the current period data
        actual_current_start = df_custom_filtered['AggregationDate'].min()
        actual_current_end = df_custom_filtered['AggregationDate'].max()
        
        # Count Response Types
        total_partials = (df_custom_filtered['Response Type'] == 'partial').sum()
        total_completed = (df_custom_filtered['Response Type'] == 'completed').sum()
        
        # Count Discovery and Intro Calls
        if discovery_col:
            total_discovery = (df_custom_filtered[discovery_col].notna() & 
                             (df_custom_filtered[discovery_col].astype(str).str.strip() != '')).sum()
        else:
            total_discovery = 0
        
        if intro_col:
            total_intro = (df_custom_filtered[intro_col].notna() & 
                         (df_custom_filtered[intro_col].astype(str).str.strip() != '')).sum()
        else:
            total_intro = 0
        
        # Use ACTUAL dates from current period data
        current_row = {
            'Date Range': f"{actual_current_start.strftime('%m/%d/%Y')} - {actual_current_end.strftime('%m/%d/%Y')}",
            'Partials': int(total_partials),
            'Completed': int(total_completed),
            'Discovery Calls': int(total_discovery),
            'Intro Calls': int(total_intro)
        }
        custom_rows.append(current_row)
        
        print(f"✅ Current period data found: {len(df_custom_filtered)} records")
        print(f"   Actual dates: {actual_current_start.strftime('%m/%d/%Y')} - {actual_current_end.strftime('%m/%d/%Y')}")
        print(f"   Total Partials: {total_partials}")
        print(f"   Total Completed: {total_completed}")
        print(f"   Total Discovery Calls: {total_discovery}")
        print(f"   Total Intro Calls: {total_intro}")
        
        # NOW calculate previous period based on ACTUAL current dates (shift by 1 month)
        actual_prev_start = actual_current_start - relativedelta(months=1)
        actual_prev_end = actual_current_end - relativedelta(months=1)
        
        # Filter data for PREVIOUS period using the shifted actual dates
        df_prev_filtered = df_custom_prep[
            (df_custom_prep['AggregationDate'] >= actual_prev_start) & 
            (df_custom_prep['AggregationDate'] <= actual_prev_end)
        ].copy()
        
        # Process PREVIOUS period
        if len(df_prev_filtered) > 0:
            # Count Response Types
            total_partials = (df_prev_filtered['Response Type'] == 'partial').sum()
            total_completed = (df_prev_filtered['Response Type'] == 'completed').sum()
            
            # Count Discovery and Intro Calls
            if discovery_col:
                total_discovery = (df_prev_filtered[discovery_col].notna() & 
                                 (df_prev_filtered[discovery_col].astype(str).str.strip() != '')).sum()
            else:
                total_discovery = 0
            
            if intro_col:
                total_intro = (df_prev_filtered[intro_col].notna() & 
                             (df_prev_filtered[intro_col].astype(str).str.strip() != '')).sum()
            else:
                total_intro = 0
            
            # Use the calculated previous period dates (shifted from actual current)
            prev_row = {
                'Date Range': f"{actual_prev_start.strftime('%m/%d/%Y')} - {actual_prev_end.strftime('%m/%d/%Y')}",
                'Partials': int(total_partials),
                'Completed': int(total_completed),
                'Discovery Calls': int(total_discovery),
                'Intro Calls': int(total_intro)
            }
            custom_rows.append(prev_row)
            
            print(f"\n✅ Previous period data found: {len(df_prev_filtered)} records")
            print(f"   Actual dates: {actual_prev_start.strftime('%m/%d/%Y')} - {actual_prev_end.strftime('%m/%d/%Y')}")
            print(f"   Total Partials: {total_partials}")
            print(f"   Total Completed: {total_completed}")
            print(f"   Total Discovery Calls: {total_discovery}")
            print(f"   Total Intro Calls: {total_intro}")
            
        else:
            print(f"\n⚠️ No data for previous period: {actual_prev_start.strftime('%m/%d/%Y')} - {actual_prev_end.strftime('%m/%d/%Y')}")
        
    else:
        print(f"⚠️ No data for current period: {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')}")
    
    # Create final dataframe
    if len(custom_rows) > 0:
        df_custom = pd.DataFrame(custom_rows)
        
        # Display the results
        print("\n" + "="*70)
        print("Custom Date Range Typeform Submissions Data (with Previous Period):")
        print("="*70)
        display(df_custom)
        
    else:
        print("\n⚠️ No data available for either current or previous period")
        df_custom = None
        
else:
    print("❌ Cannot generate custom analysis - dates not properly specified")
    print("   Please check Custom Start Date and Custom End Date in analysis_ref_date.csv")
    df_custom = None

print("\n" + "="*70)

======================================================================
CUSTOM DATE RANGE TYPEFORM SUBMISSIONS AGGREGATION (WITH PREVIOUS PERIOD)
======================================================================

Current Period (Requested): 11/01/2025 - 11/28/2025 (28 days)
Previous Period (Requested): 10/01/2025 - 10/28/2025 (28 days)

✅ Current period data found: 183 records
   Actual dates: 11/01/2025 - 11/07/2025
   Total Partials: 37
   Total Completed: 146
   Total Discovery Calls: 123
   Total Intro Calls: 23

✅ Previous period data found: 87 records
   Actual dates: 10/01/2025 - 10/07/2025
   Total Partials: 20
   Total Completed: 67
   Total Discovery Calls: 52
   Total Intro Calls: 15

======================================================================
Custom Date Range Typeform Submissions Data (with Previous Period):
======================================================================

                Date Range  Partials  Completed  Discovery Calls  Intro Calls
0  11/01/2025 - 11/07/2025        37        146              123           23
1  10/01/2025 - 10/07/2025        20         67               52           15

======================================================================

### Save Custom Date Range Data

In [18]:
if df_custom is not None and len(df_custom) > 0:
    # Save to CSV
    custom_path = os.path.join(output_dir, 'custom_typeform_submissions.csv')
    df_custom.to_csv(custom_path, index=False)
    
    print("\n" + "="*70)
    print("CUSTOM DATE RANGE ANALYSIS - COMPLETE")
    print("="*70)
    
    print(f"\n✅ OUTPUT CREATED:")
    print(f"  - custom_typeform_submissions.csv")
    
    print(f"\n📁 Saved in:")
    print(f"  - {custom_path}")
    
    print(f"\n📊 File Details:")
    print(f"  - Shape: {df_custom.shape[0]} rows × {df_custom.shape[1]} columns")
    print(f"  - Rows: {len(df_custom)} (current + previous period)")
    if custom_start and custom_end:
        print(f"  - Current Period: {custom_start.strftime('%m/%d/%Y')} - {custom_end.strftime('%m/%d/%Y')}")
        print(f"  - Previous Period: {prev_start.strftime('%m/%d/%Y')} - {prev_end.strftime('%m/%d/%Y')}")
        print(f"  - Duration: {(custom_end - custom_start).days + 1} days each")
    
    print(f"\n📈 Columns:")
    print(f"  - Date Range")
    print(f"  - Partials, Completed")
    print(f"  - Discovery Calls, Intro Calls")
    
    print("\n" + "="*70)
else:
    print("\n⚠️ Custom analysis not saved - no data to save")
    print("   Check date range and data availability")

======================================================================
CUSTOM DATE RANGE ANALYSIS - COMPLETE
======================================================================

✅ OUTPUT CREATED:
  - custom_typeform_submissions.csv

📁 Saved in:
  - ../outputs/typeform_submissions/custom_typeform_submissions.csv

📊 File Details:
  - Shape: 2 rows × 5 columns
  - Rows: 2 (current + previous period)
  - Current Period: 11/01/2025 - 11/28/2025
  - Previous Period: 10/01/2025 - 10/28/2025
  - Duration: 28 days each

📈 Columns:
  - Date Range
  - Partials, Completed
  - Discovery Calls, Intro Calls

======================================================================

### Verification - Preview Custom Date Range File

In [19]:
if df_custom is not None and len(df_custom) > 0:
    print("Custom Date Range Typeform Submissions Preview:")
    print("="*70)
    display(df_custom)
    
    print(f"\n✓ Custom date range analysis completed successfully!")
    print(f"  File location: ../outputs/typeform_submissions/custom_typeform_submissions.csv")
else:
    print("⚠️ No custom data available to preview")

Custom Date Range Typeform Submissions Preview:
======================================================================

                Date Range  Partials  Completed  Discovery Calls  Intro Calls
0  11/01/2025 - 11/07/2025        37        146              123           23
1  10/01/2025 - 10/07/2025        20         67               52           15

✓ Custom date range analysis completed successfully!
  File location: ../outputs/typeform_submissions/custom_typeform_submissions.csv